### ISSUE TITLE
TOPIC: Save changes and Publish topic not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1037]
**What is the problem?**
_Tested in Google Chrome in Mac OS and Android_

User is not able to Save Changes and Publish 
https://drive.google.com/file/d/1dH4pEnacPbjPHEXcsEhYy2kQpnQbQzqn/view?usp=sharing

However, the topic is later added to the database and notifications are sent out (if the topic has been added to a group)

**Why is this a problem?**
User cannot perform any actions, including navigating the page, as it appears to be stuck. 

**Possible solution.**
Save changes and Publish should lead the user to the duplicated topic with a success message.

**Comment by ilmartyrk** [comment]
@ssin1901 thank you for catching this, I revamped the whole edit/change topics process so that users get UX as per design with the whole save changes and publish buttons and also notifications if they have unsaved items and start navigating away. Anyway fixed the issue and it was only related with topic edit view
