### ISSUE TITLE
Topics: Public topics default sorting is misleading (due to 'Last edit' bug?)  

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1055]
I thought for a minute that we had a new public group, as it seemed like it had recent activity, but then I noticed the date was 2017.. When I came out of it, the 'Last edit' button says a minute ago, but I believe it was just me going into it and looking at it that made it say that? So is there something not working correctly with 'Last edit' that means public topics which haven't had activity for years (7 in this case) are displayed at the top as if they are active? 

(Probably the same for all the other topics here, that look quite recently active from the 'Last edit' but are likely also very old ones?) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c8136611-3074-4adf-8f73-7d1458769966)

**Comment by BeccaMelhuish** [comment]
I also notice now that the creation dates are incorrect too: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/26d3b770-68b4-437c-b36a-a13ac316d127)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish I checked this issue, and there was a bug on the API side, every time a topic was opened it synced the authors list with Etherpad and run the update command to update the authors list in API database, and that created the new timestamp for topic update. 

For the top date I used the timestamp when the topic was updated and the bottom one was for the latest activity time. I posted a fix for that too so that the top date is the creating date
