### ISSUE TITLE
IDEATION: 'Add discussion' block for ideation topic

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1172]
When a user makes a new ideation topic, and they haven't yet opted to add a discussion phase, this block should be 'Add discussion' (and clicking on it makes these stats appear thereafter, and takes the user to the discussion tab where they can then start posting), rather than showing all the stats as zero.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/563a6b0b-98ce-48aa-b561-298a9d003cca)

Tagging @kevincrepin in case he disagrees or has something to add (it's not in the designs as we started with discussion there) :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin updated the item if no arguments are added and topic ideation is in progress it has text no discussion yet and dashed borders

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @kevincrepin I feel like this needs some thinking through re adding phases - as in this case an admin can't actually 'add' a discussion phase, they can only launch a discussion phases by adding an argument. And it also means a participant can add a discussion phase when the admin hasn't intended there to be one, by simply adding an argument. Feels like potential for quite some messiness/lack of control by the admin, which in some cases could be problematic/mess up the process.. 

But I will make a new issue from this comment and I think this one can be closed :)

**Comment by kevincrepin** [comment]
Maybe I'm misunderstanding...

What the admin sees since they can add the phase:
![Screenshot 2024-05-15 at 12 11 23](https://github.com/citizenos/citizenos-fe/assets/26792281/4c6ec36c-43c7-4ebb-b1cf-ca3966951586)

What participant sees until the phase is added:
![Screenshot 2024-05-15 at 12 17 17](https://github.com/citizenos/citizenos-fe/assets/26792281/10b1bbac-4fe3-4cc2-af2d-0e953805f9de)

This can work the same here, no? :)
