### ISSUE TITLE
IDEATION: Deadline section bugs in test platform in topic creation flow

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1220]
This is what it looked like for the user, and the only editable bit was the top row. (Test platform). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/607bf3ae-62f7-41d9-bf70-e565811ab296)

**Comment by ilmartyrk** [comment]
I could not replicate it, can you add more info, what the user did step-by-step, also possibly browser.

**Comment by BeccaMelhuish** [comment]
The browser I'm not sure of but can try to find out, but what he did was quite straightforward, just creating an ideation topic and got to this bit and it was like this. And also when going back to try editing it several times it was always like this. Will keep an eye in the other tests, but maybe @ssin1901 can try to replicate too?

**Comment by ssin1901** [comment]
@BeccaMelhuish I also could not replicate it on Safari or Chrome. Can I/we ask the user which browser they were using for the test?

**Comment by BeccaMelhuish** [comment]
Just noticed that the same thing happened (and something new, going off the edge) when he was in the voting deadline dialog too. Have asked for browser will update when I have it :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/5ce120b8-5566-47f2-bac8-6e46d2849798)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 something funny going on for this user too, who was using Safari (awaiting reply from the other one still). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/bf830beb-29ff-40ea-9367-7da2b1ebfcff)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk @ssin1901 The same issue came up every time the user came to the deadline part in a pop-up window as per the screenshots below, she was using Firefox: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/03c75d84-d5ab-41c6-93f2-a8f0d985abc5)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/01dedd78-219f-48f2-bf40-957436bcfa0c)

**Comment by ssin1901** [comment]
@BeccaMelhuish ran the deadline tests and could not replicate in any of the browsers in the test environment. Will close, but not moving to Done because I want to keep an eye on it.

![check-if-discussion-deadline-appears-1-mobile-webkit-win32](https://github.com/user-attachments/assets/786427df-1793-45a1-b747-f7b05742fc2c)

![check-if-discussion-deadline-appears-1-Galaxy-Note-3-win32](https://github.com/user-attachments/assets/5de36fb5-5bcf-4b0c-8f72-4a13e5295c3e)

![Check-deadline-in-create-ideation-1-iPhone-SE-win32](https://github.com/user-attachments/assets/5508e3a5-736f-4dd9-a8be-84ddc1682602)

![Check-deadline-in-create-ideation-1-Galaxy-Note-3-win32](https://github.com/user-attachments/assets/9b86cc4d-a057-4dd8-b9dc-a8ca09118303)

**Comment by BeccaMelhuish** [comment]
@ssin1901 moving back to testing for you as I think the bot did what you didn't want :)
