### ISSUE TITLE
IDEATION: View for adding to folder when there are no folders

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1222]
@kevincrepin @ilmartyrk 

**Ideation Round 1 UX tests insight:** 

Only from 1 test but seems like a UX bug rather than comprehension issue, so reporting already. When user clicks 'Add to folder' on an idea before they have created any folders, this is what they get (below). 

**Suggestion:**

Should there be something allowing them or prompting them to create a folder here? Or should 'Add to folder' be greyed out in the idea's '3 dots' menu when there are none to add it to?   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2bbb77e9-b00e-4f81-abf4-87b2db6914c1)

**Comment by kevincrepin** [comment]
Yes, let's do it so that a new folder can be created from here and the idea can be added to it immediately.

We can have a checkbox "add to new folder" and once checked a text field appears where the folder name can be added.
![Screenshot 2024-05-23 at 10 19 44](https://github.com/citizenos/citizenos-fe/assets/26792281/86100761-42e0-4c58-9182-80697efbd4a1)
![Screenshot 2024-05-23 at 10 19 54](https://github.com/citizenos/citizenos-fe/assets/26792281/38eb9886-c455-4671-a9bb-9b2854e76b8c)

@ilmartyrk updated design is here: https://www.figma.com/design/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=452%3A65746&t=EMOUbT1rZWEDxBuy-1

**Comment by ssin1901** [comment]
@BeccaMelhuish add to folder has been removed from topics where there are no ideation folders (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/306e2bf7-6e8e-407e-b206-ea51dfac47e2

**Comment by BeccaMelhuish** [comment]
Tested and a few things :) 

This bit's a bit odd, with zero folders pre-selected. @kevincrepin what should it look like here when there are no folders? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1f9490e5-550a-4502-82a4-efee9b266a27)

As per @ssin1901's screen recording, 'Add to folder' isn't in that menu, only in the one inside the idea. Both should be the same I guess, or @kevincrepin it's correct that it's only in the internal one? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3b9ec997-cdb1-4071-8aa8-7133e3f27c6a)
 
Once I added my idea to the folder, nothing happens. There should be a message, 'Idea added to folder!' or something similar?  

https://www.loom.com/share/3c63b1a74fcb48029e43ff527e39c6ed?sid=dda1a862-fd8b-4fec-8dca-bf9e3ec87c84
