### ISSUE TITLE
BUG: Missing groups from add topic to group list

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-fe#1259]

**Comment by ilmartyrk** [comment]
est. dev time 30 mins.

**Comment by ssin1901** [comment]
@ilmartyrk in Google Chrome incognito mode, the topic list keeps changing. This session while creating an idea gathering topic – AI general demon and some other topics that I have topic admin permissions for did not appear in the list (see screen recording)

https://github.com/user-attachments/assets/147d4275-1576-4f4a-9a18-04b8bac7f08e

**Comment by ilmartyrk** [comment]
what browser are you using, the groups should be there, but for some reason you are not able to scroll to them

**Comment by ssin1901** [comment]
@ilmartyrk Google Chrome in incognito mode. The views seem to change randomly.

The first time I tested it with a new topic, it worked as expected with correct list and scrollbars (screenshot1) but now I'm getting this (screenshot2)

<img width="1037" alt="Screenshot 2024-08-21 at 10 58 21" src="https://github.com/user-attachments/assets/2c891ff9-5b8b-42f0-b761-d5b2e6b4da22">

<img width="1350" alt="Screenshot 2024-08-21 at 10 56 31" src="https://github.com/user-attachments/assets/792356dd-b493-4845-a829-3ef4ecdfd274">

But I guess the issue is no longer related to missing groups from add topics list? And should be a new issue?

**Comment by ilmartyrk** [comment]
Yes, all groups are there
