### ISSUE TITLE
INVITES: Users landing on DB after following email invite or share link

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1294]
@ilmartyrk I remember you fixed it previously so that following an invite to a group or topic (via email or share link), users would be taken directly to the topic or group they were invited to. 

In the tests, this hasn't been happening - they've been landing on the DB after following the invite and making their account. Is this just a test app thing, or the previous fix has stopped working?

**Comment by BeccaMelhuish** [comment]
Will add high priority tag as should be fixed before launch :) 

(@ssin1901 I assume it's working OK on the live one? Steps being follow link - make an account/login - arrive into the topic/group they've been invited to)

**Comment by ssin1901** [comment]
@BeccaMelhuish this is currently the view when a user has received an invitation to a Private Topic and created and verified their account (screenshot1, screenshot2, screenshot3). I think it looks alright but please correct me if this is not the expected view.

<img width="1378" alt="Screenshot 2024-07-09 at 20 27 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1257668c-04e8-4c8b-b017-f4ac6e56b2bf">

<img width="1382" alt="Screenshot 2024-07-09 at 20 24 24" src="https://github.com/citizenos/citizenos-fe/assets/72747107/54890386-c9af-4ade-be36-b80ae0d38fe0">

<img width="1388" alt="Screenshot 2024-07-09 at 20 24 36" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6abe7e60-4f00-40d7-8ea1-539f80f14780">

I am having a few issues with testing a Public Topic due to #1383

**Comment by ssin1901** [comment]
@BeccaMelhuish will mark this one as Done as well 

(https://drive.google.com/drive/folders/1aMjUP1nqZSOaScWr5KIOsB_M5i2LaCd2?usp=sharing)
