### ISSUE TITLE
IDEATION: Should other replies display when you start adding your reply? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1325]
@kevincrepin, I'm labelling with 'user insight' as it came out of watching a user test, but is more just a question from me rather than something from a user - what would be the standard/good practice UX in this case? 

The user (older, lower IT skills) opens the idea, doesn't open the replies (whether he hasn't seen that there is one or isn't interested, I'm not sure) and clicks 'Reply'. When he clicks reply, should the other replies automatically open up so he can see what others have replied (it seems to me that they should?), or it's OK that he replies without having seen the others? 

Currently it goes like this: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e5a3226d-bf36-41ca-9223-18925d589c42)

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/57155b2e-9969-49ea-81f6-dee2b69aa79d)

And only then does he see the other reply(/ies):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8cf4b34f-3489-4a99-a887-f62c15ef64f2)

**Comment by kevincrepin** [comment]
Hmmm if we would open automatically the replies we also create the potential scenario if there's a lot of replies and then they all open it might be disorienting, so that's the other side of this...

I would keep it as it is and gather more feedback before making changes to this. The button to view the other replies is right there next to the "reply" button.
