### ISSUE TITLE
FOLLOW-UP: UX insights on Action phase

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1373]
@ilmartyrk @kevincrepin 

**Round 2 insights on the Follow-up/Action phase**

- The word 'Action' seemed to cause less confusion than 'Follow-up'. Though a couple of people expected that in would be about actions the participants can take themselves - volunteer, donate, etc. 
- One team of users (2 admins working together), pointed out that the pink 'Flag' icon on mobile meant that they expected it was to do with 'flagged' content, as they are used to it meaning that elsewhere. 
- Admins would like to be able to add attachments to their updates. 

**Suggestions**

- I think we can leave it as 'Action' for now. The confusion was only slight, and rectified upon seeing the updates. 
- Is there another icon we could use for the action phase on mobile? I guess a megaphone could work - as the updates are kind of announcements, but this might also be associated with 'activism', as in 'Go out and protest' in some contests.  
- Could we allow adding attachments to updates? (I guess this is a bigger fix @ilmartyrk, as it was with adding to ideas/replies?)

**Comment by kevincrepin** [comment]
Feels a bit like the flag comment is anecdotal so I wouldn't immediately change it. Within the context it should be clear that this is not an indication of flagged content. However if it comes up still several times then we can revise, of course.

Adding attachments in line with how it currently is in topic creation:
![Screenshot 2024-07-05 at 15 03 32](https://github.com/citizenos/citizenos-fe/assets/26792281/7df0533d-91f7-4507-b53d-67d24f08d41a)

**Comment by kevincrepin** [comment]
TO me it seems the flag comment is a bit anecdotal and not sure if we should change it for this reason. The context should make it clear it's not indicating flagged content and we're not using a flag icon for any reporting action iirc. I would keep it for now as it is, but of course if this comment pops up again then we can revise.

Since the posting updates has updated a bit from what's designed I added a reference for the adding attachment:
![Screenshot 2024-07-05 at 15 08 48](https://github.com/citizenos/citizenos-fe/assets/26792281/0ea7318f-c57e-47c6-88b8-40ebc03a1a09)

**Comment by BeccaMelhuish** [comment]
OK yes makes sense re the flag! Will just keep an eye on it :) 

And great, attachments look good.

**Comment by BeccaMelhuish** [comment]
I've made [this issue](https://github.com/citizenos/citizenos-fe/issues/1512) for adding the attachments now, so will close this one :)
