### ISSUE TITLE
VOTING: User confusion around e-ID voting being Estonian only

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#1377]
@ilmartyrk @kevincrepin 

**Insight from Round 2 ideation testing**

This is only from one user, but seems an important one so will share. An admin in Indonesia selected 'Hard voting' for her vote. She obviously hadn't realised that it was only for those in Estonia. This makes sense, as it looks like they have e-ID in Indonesia too. She didn't at any point during the test realise her error. 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/3b74d85b-6ff1-44cb-8c88-b20fd95f423a)

**Suggestion**

It seems there could be room for confusion in any other country that has eID. And if someone starts a vote with eID, they currently have no way to edit this, as it's not possible to edit a vote once you've started. Which could really mess up someone's process if they hadn't tested it before-hand. 

@ilmartyrk Is it possible to only show the e-ID option in vote settings when someone is based in Estonia? 

@kevincrepin Another option is that we add some text to make it clear it's 'Estonia only' or 'Estonian e-ID', but this doesn't seem ideal as we're an internationally-focused platform..

**Comment by kevincrepin** [comment]
Let's not use IP as a basis to show specific features because it doesn't always work well and people can use VPNs.
I think it was always the idea to support other countries digital identification methods, but this is probably not a 5 minute job :)

So I think in the short term we might have to fix this with copy:
![Screenshot 2024-07-08 at 11 57 36](https://github.com/citizenos/citizenos-fe/assets/26792281/a041cb85-38ae-49b2-9801-49c6681bfde9)

But thinking long term then it becomes a bit more complex. I would say the user should choose which country (or countries) they would like to support. It makes sense that it would – eventually – support multiple countries and the user could also choose multiple country digital identification methods.

Step 1:
![Screenshot 2024-07-08 at 11 59 32](https://github.com/citizenos/citizenos-fe/assets/26792281/d4229ce9-c2d9-4b19-a0c5-eab2ca40d55f)

Step 2: 
![Screenshot 2024-07-08 at 11 59 54](https://github.com/citizenos/citizenos-fe/assets/26792281/09c9a2de-4f58-425a-9b0f-9a8ef585bfd0)

Step 3:
![Screenshot 2024-07-08 at 12 00 11](https://github.com/citizenos/citizenos-fe/assets/26792281/bf885987-d2d6-48f8-b227-fa2e36154174)

But I'm sure this is easier said then done and no idea what the implications are from a technical and regulatory/law-level, so I'll leave that up in the air :D

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK nice! I've updated the text in the ideation branch strings to "(only in Estonia for now)", then we can revisit the topic when we're at the stage of adding more countries one day :) 

@ilmartyrk do we leave this issue open until then, or close it for now?

**Comment by BeccaMelhuish** [comment]
I will close it :)
