### ISSUE TITLE
Responsive layout issue

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#145]
@ilmartyrk @anettlinno @ssin1901 
When making my browser smaller the search bar moves down and covers up the top section of the screen. 

It goes from this:
![image](https://github.com/citizenos/citizenos-api/assets/61320526/8ca09ac7-6616-44ad-b622-1d48dad00483)

To this: 
![image](https://github.com/citizenos/citizenos-api/assets/61320526/adf58df0-da11-4d43-acb2-2c6b5a47aead)

Sometimes it just looks ugly, but sometimes it covers up important stuff that's at the top of the screen

**Comment by ilmartyrk** [comment]
@BeccaMelhuish, @anettlinno  this is because some elements are added or removed with scripts during page load and at the same time we have dynamic styles for different devices. So if you only use certain device it will not appear, but if you resize your window it will appear. I will not fix this for current version, but will look if this can be avoided during redesing.

**Comment by anettlinno** [comment]
Triage 86. As Ilmar said, we´ll not fix this in current version but we´ll send it to redesign project.

**Comment by ilmartyrk** [comment]
Old platform issue
