### ISSUE TITLE
IDEA GATHERING: 'Start topic voting' text needs to change

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1506]
**What is the problem?**
_Tested in Google Chrome in incognito mode_

A user cannot add a Discussion to an Idea Gathering at any time. The text should reflect this. Currently this is what it says (screenshot1)

<img width="1196" alt="Screenshot 2024-08-21 at 17 19 08" src="https://github.com/user-attachments/assets/938c6d1d-578d-4bbc-99bc-235bc23a6f28">

**Why is this a problem?**
Misleading to users AND Customer Support who would also assume that Discussion can be added at any time.

**Possible solution.**
@BeccaMelhuish any thoughts regarding the text?

**Comment by BeccaMelhuish** [comment]
@ssin1901 I remember now that we do already have two different texts - one for topics that go idea gathering > voting, and one for topics that go discussion > voting, so this should be a simple fix for @ilmartyrk :) 

**For topics that start with idea gathering, and move to voting without a discussion phase added (i.e. there is neither a discussion question nor contributions):**  
(With some other minor tweaks for other reasons, spotted on review. Bold are the orange texts, NEW etc are just for reference here)

**X You can no longer (co-)edit your topic text**
**X Participants can no longer add, edit or like ideas**
**X You can no longer add a discussion phase** _- NEW_
X You can't edit a vote once you have started it
X You can't start more than one vote per topic _- EDITED (already fixed in strings)_
You can still invite and share with participants
Participants can still read, favourite and reply to ideas _- EDITED_

And just FYI @ssin1901, but no changes needed :)  
**For topics that start with discussion then move to voting:**  

**X You can no longer (co-)edit your topic text**
X You can't edit a vote once you have started it
X You can't start more than one vote per topic
You can still invite and share with participants
Participants can still continue to have a discussion

**Comment by ilmartyrk** [comment]
@BeccaMelhuish added the new text, 

I have to add a note that when creating a task list for a developer try to keep it as low on information as possible it took me quite a long time to finally understand that I only have to add 1 line of text to the translations and to the dialog :), In this case only the position(s) of the text(s) might have been necessary to understand where they need to go, everything else was too much

**Comment by BeccaMelhuish** [comment]
Noted thanks so much @ilmartyrk! I think here I was trying to give the overall picture to Sara of what the solution will be as well, but should indeed have separated out the task for you, makes sense :)  

Tested it and all looks good moving to Done :)
