### ISSUE TITLE
Idea Gathering: Multiple images leads to Add Idea/Add Image/Cancel buttons disappearing

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#1589]
**What is the problem?**
_Tested in Google Chrome and Safari_

No limit mentioned for how many images can be added to a topic. However, adding 7 attachments lead to this view where Add Idea/Add Image/Cancel disappeared/could not be scrolled down to, and the user could no longer interact with the page (screen recording1)

https://github.com/user-attachments/assets/125bc9a3-d7b7-4947-87c0-c13076bc057a

**Why is this a problem?**
@ilmartyrk @BeccaMelhuish marked as high priority only because in this scenario, the user has no option but to exit the page. Please remove the high priority label if you think that it is unlikely that a user would find themselves in this situation

**Possible solution.**
1. Adding an image limit - maybe 5 images?
2. Buttons should be visible no matter how many images are added

**Comment by BeccaMelhuish** [comment]
Good catch thank you @ssin1901! @ilmartyrk if we can make it so that they can add as many as they like (no point limiting them unless we have to), but so the buttons are all still viewable, would be perfect :) 

I'm also hesitant to have it as a high priority, as probably rare users will add more than 7, but let's keep it as such for now and discuss on Weds?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish  @ssin1901 I will add scrollbar to the right

**Comment by ssin1901** [comment]
@BeccaMelhuish scrollbar seems to work well! (screen recording). Moving to Done.

https://github.com/user-attachments/assets/634f6d35-8235-4fab-b728-5c09ab22918e
