### ISSUE TITLE
Misleading group rights when it comes to topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#173]
**What is the problem?**
1.A user can only select topics for which they have admin rights. They then see the option to change the topic rights directly from the group interface (screenshot attached). In this case it is participant.
<img width="781" alt="Screenshot 2023-07-20 at 22 28 29" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f33663a4-4371-4661-a4b8-78dd2ffa6cd9">

However, this is misleading as it directly contradicts what is shown in the interface for that topic where both users are admin (screenshot attached).
<img width="1249" alt="Screenshot 2023-07-20 at 22 28 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d4315db5-4236-4d7e-99be-6709ad54ba7b">

**Why is this a problem?**
Very difficult for groups to manage topic access. They do not understand who has participant rights and who has admin rights.

**Possible solution.**
The admin users from the topic should be shown in one column with their admin rights (which can be changed only from the topic interface). There should be a second column for NEW users who would automatically be assigned participant rights.

Also Help Centre update needed regarding this.

**Comment by anettlinno** [comment]
From Slack discussion with @ssin1901

Here is the issue step-by-step:

1. User Alex creates a topic [Alex topic] and adds Sara as admin
2. Sara creates a group and adds [Alex topic] to the group
3. In the group view, Roles are set to participant and 2 users are shown [Sara + Alex]

_How does Sara know which rights she and Alex have now? Admin or participant? What happens if she changes it to Editor? Does she lose her admin rights?_

**Comment by ssin1901** [comment]
Hey @anettlinno @ilmartyrk just retested the issue and to me it is persisting. It might just be an issue with our UX/flow but it is still an issue, in my view.

1. Step 1 - Created a topic 
<img width="1290" alt="Screenshot 2023-09-18 at 17 25 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/77f53078-5a1b-4b84-9393-c4092dd5dd3c">

2. Step 2 - Added Alex with ADMIN rights

<img width="1288" alt="Screenshot 2023-09-18 at 17 26 17" src="https://github.com/citizenos/citizenos-fe/assets/72747107/c15c3789-b556-482d-ae7c-ac1be1c3c35e">
<img width="1201" alt="Screenshot 2023-09-18 at 17 27 02" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cee122a4-2ba1-44e0-97ad-5f88b74c0090">

3. Now I create a group. Add the same topic to the group. I see one column for setting rights. See 1 more column for for users, which is set to 2. Rights column says PARTICIPANT
<img width="1289" alt="Screenshot 2023-09-18 at 17 27 48" src="https://github.com/citizenos/citizenos-fe/assets/72747107/f09a376c-7517-4ea0-9da7-e98e1d1902c8">

4. When I go back to my topic or Alex goes back to the topic, the topic still says ADMIN for both
<img width="1202" alt="Screenshot 2023-09-18 at 17 28 21" src="https://github.com/citizenos/citizenos-fe/assets/72747107/60a195d2-7781-4f05-b241-f5f0d04a17a6">

5. Now, I go back to the group, and change the _topic_ rights to Editor

<img width="1290" alt="Screenshot 2023-09-18 at 17 33 16" src="https://github.com/citizenos/citizenos-fe/assets/72747107/773246a3-1720-4f16-b955-6f4c88ee3c1b">

6. Go back to the topic and see that Alex STILL has Admin rights
<img width="1202" alt="Screenshot 2023-09-18 at 17 33 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/4d8141c4-3508-4259-bce0-6b2300b52c51">

7. Meanwhile, Alex gets notified that the group rights are changed, when he is isn't even part of the group. When he tries to click on the group he gets this error

<img width="1203" alt="Screenshot 2023-09-18 at 17 41 46" src="https://github.com/citizenos/citizenos-fe/assets/72747107/cc2ca6c7-bdf2-4e7e-a457-5a53741dbcb3">

8. And throughout, the rights of Alex remain the same. ADMIN. Not Editor. 
<img width="1204" alt="Screenshot 2023-09-18 at 17 43 49" src="https://github.com/citizenos/citizenos-fe/assets/72747107/258476d9-875f-4f57-b3de-ad8f5ca7badb">

9. Now I add Alex as a member. 
<img width="1288" alt="Screenshot 2023-09-18 at 17 54 37" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1a52bb3a-3a28-4766-a9aa-52d271b04205">

10. Under topic rights, the "default" setting for the topic is Editor
<img width="706" alt="Screenshot 2023-09-18 at 17 57 23" src="https://github.com/citizenos/citizenos-fe/assets/72747107/df54f473-45ed-402a-9fea-9862e2168bb1">

11. I would assume that now that I have added Alex to the group, as a new member the rights of Alex would be changed to Editor. But no, still Admin
<img width="1202" alt="Screenshot 2023-09-18 at 17 56 01" src="https://github.com/citizenos/citizenos-fe/assets/72747107/8c4fc813-5131-495a-8887-8f25ed44da13">

Problems/questions*
1. Default functionality: topic rights can only be set in the group topic list for group members. Previous people retain their rights, whether they are group members or not. 

But why are the words "Manage topic rights for Members" not written anywhere in the group interface? Only topic list? When clearly you cannot manage the TOPIC members from the GROUP interface

2. Why can the group owner not see _which_ topic members are also group members, and which members are only topic members? Why just one single count of 2?

3. Why does Alex who is not a group member get notified about changes to the group rights in the activity feed? Alex cannot not even access the said group, gets a no permissions error

4. Even after adding Alex as a group member, the rights of Alex can be managed only via the topic interface. This is understandable as topic rights supersede the group rights. But shouldn't I, as the group owner KNOW from the group interface which of my group members have Editor rights and which have Admins? 

NB! @anettlinno @ilmartyrk I also added the two of you as participants to the group. Since I have set the permissions to Editor, I assume you both would be able to access the topic and have Editor rights.

**Comment by ilmartyrk** [comment]
@ssin1901 @anettlinno I believe we have had this discussion before, but to keep it simple, highest permission is counted. In this case admin permissions were directly given to Alex so these overpower the group permissions. If we decided to change permissions for each member of each group to single topic it would be complete mess. Imagine a case where a person is a member of 3 groups and each group has different level of access. But these are given in a random order, this would mean that topic admin would have to start managing permissions for each user separately also trying to keep account when to change what groups permissions etc.

1)  Group permissions can be changed only from my topics view as user has to have admin access to topic to add it to group. 
Manage topic rights for Members is meant for managing rights for topic members not groups members, these are different lists of users.
2) That is because topics and groups are different entities, you might be owner of a group but not have these permissions for the topic.
3) Alex is admin of the topic so he gets notified about permission changes related to that topic 
4) I'm little confused what you are expecting here, to see single topic permission for each user under group view? You can see all permission for a topic in topic view, if a persons permissions come from group they have extra text there that these permissions come via group

@ssin1901 hope you are not overthinking it, but please let us know what are your expectations for your use-case

**Comment by ssin1901** [comment]
@ilmartyrk thanks for the detailed explanation! The issue is with the UX, not the flow. I think it not a bug but rather a redesign enhancement, and maybe we can change the label. 

My expectations

1. In the future, I would have two separate tabs for topics within a group and members within a group. Then the user will understand better what they can and cannot do. **NB! This is perfect in Redesign.**

2. Alex who is a topic admin and **not a group member** should receive a notification stating __ user Sara has modified topic permissions within a private group, along with the permissions level. The group is private and therefore the name should not be disclosed to a non-member. 

But privacy aside, as a non-member, Alex should _not be able to click on the link with the group information_ from the activity feed because he will receive a Not Found message, which is frustrating for users. 

Also sorry we have to go through the whole flow again, I think this an enhancement not a bug. When I opened the ticket, I probably didn't know the flow. But when I retested the flow, the Alex receiving a clickable notification that led to a You do not have permission to complete this operation, looked like a bug.
