### ISSUE TITLE
Code in Deleted Argument->Why

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#176]
**What is the problem?**
When a user deletes their argument and then tries to view it under This topic was deleted->Why (screenshot attached). 

<img width="1247" alt="Screenshot 2023-07-31 at 14 37 09" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6a451100-3ca4-4b75-ac17-e645172b0588">

**Why is this a problem?**
Confuses the user 

**Possible solution.**
There should be no code in the Why description. Also @ilmartyrk maybe we need to rethink this for Redesign. The user deleted their own topic but the text says "was found to be inappropriate". This is misleading and inaccurate as the reason the user deleted could have been duplicate but they were not asked to provide a reason.

**Comment by anettlinno** [comment]
Triage 89. The link is leading to "Citizen OS Topic Moderation" topic in our public group (but currently it is named as to Code of Conduct which is misleading) and this is important link. 
@ssin1901 do you have any better wording to suggest instead of "This argument was found inappropriate" which could be relevant to all different kinds of use cases (like inappropriate content moderated by moderators, deleted by author for any reason etc).
Code fixing estimation 10 min. Sending it To Do.
