### ISSUE TITLE
Invite and share character limit warning missing 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#18]
**Specifications**

MacOS Safari

**Problem**

When the user clicks on Invite & Share and enters text for "Add an optional topic invitation", they are limited to around 1000 characters but the user receives no directive nor warning indicating that there is a character limit (screenshot attached).

<img width="1438" alt="Screenshot 2023-02-28 at 00 15 28" src="https://user-images.githubusercontent.com/72747107/221698842-ed387adc-9a69-4d73-b41e-d92f66908a16.png">

**Expected result**
User should receive a directive that they can only add up to 500/1000 characters. Ideally the number of characters should also be counted and the text colour should become red when the character limit is exceeded.

**Comment by ilmartyrk** [comment]
The limit should actually be automatically set so you cannot enter text that is longer, the input won't allow it, but could you re-check if it actually works in safari/chrome, the limit is 1000 characters for reference

**Comment by anettlinno** [comment]
Triage 83. Please add character limit number behind the text: _Add an optional invitation message (character limit 500)_

Additionally, please autoresize text area when entering longer text (so that window would automatically adjust according to the text length). 

Est. dev. time 1 hour. Sending the issue to Development.
