### ISSUE TITLE
Mobile view right sidebar alignment in Create Topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#195]
**What is the problem?**
Mobile view causes a lot of issues for the users in Create Topic mode. When a user resizes the window (screenshot attached)

 
<img width="1346" alt="Screenshot 2023-08-17 at 11 27 19" src="https://github.com/citizenos/citizenos-fe/assets/72747107/3b98832e-e73a-4e4a-9e08-3bc610ad1556">

to a smaller viewport size, the edit and right sidebar menu are no longer accessible (screenshot attached)
<img width="1340" alt="Screenshot 2023-08-17 at 11 26 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/99496bc4-272a-4c28-98ed-8c2048860e43">

When a user accesses it on a mobile device (in this case iPhone 6S) there is a pencil icon that disappears when clicked (screenshot attached)

![IMG_5674](https://github.com/citizenos/citizenos-fe/assets/72747107/e03ddb3a-eac0-42e5-b628-edf94f6b4a74)

**Why is this a problem?**
It is very difficult for a user to Create a Topic in different viewports. Issue occurs across Safari and Chrome. 

**Possible solution.**
The Edit Topic and Right Sidebar Menu alignment and display need to be fixed across different screens.

**Comment by ilmartyrk** [comment]
Triage 88, when user resizes the view manually from desktop to mobile or other way around some elements will change from stylesheet info CSS, but for some components we do window width checks inside javascript because some components will have to be rendered in another place inside code depending on the device. This code part that checks the width is only triggered while loading the view and if you resize the page manually it will show the component that was initially loaded, will close this issue for now as it is not a common usecase

**Comment by ssin1901** [comment]
@ilmartyrk not so important for the current platform, but our partners might test responsiveness on the Redesign using browser tools. I almost used the Safari developer tools myself to illustrate the responsiveness.
