### ISSUE TITLE
Public groups: Same user invited twice but with different invite status

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#21]
**Specifications**
MacOS Google Chrome

**Problem**
When a user invites a participant who is already a member of the topic, they see the user under Manage Participants (see screenshot) but also under invited (see screenshot)

<img width="1439" alt="Screenshot 2023-03-07 at 22 46 24" src="https://user-images.githubusercontent.com/72747107/223549360-26718d6e-4ee5-4847-9935-a6e0a8a30a39.png">

<img width="1438" alt="Screenshot 2023-03-07 at 22 46 33" src="https://user-images.githubusercontent.com/72747107/223549374-e4d74cca-2963-45b4-b20e-02a3cff87376.png">

**Expected Result**
Message "This participant is already a member of this topic".

**Comment by ilmartyrk** [comment]
Things  to note:
1) User is member because he/she is a member of a group that has been added to the topic
2) Also a personal invite has been sent out to a user
 
We can see from the members list where the user has gotten their permissions from, if it is via group it is from group if not it is direct. This might be more of an issue when the group and personal invite have same permissions then it looks a little weird, but in the case  where personal invite permission level is higher than the groups level we still need the person to accept the invite.

Anyway I will put this issue on hold and we need to think about it a little more, this is rather an UX issue than a BUG

**Comment by ilmartyrk** [comment]
Trigate 83. Update Invited users list API endpoint to filter out users who have already got access to topic via group.
