### ISSUE TITLE
Smart ID not working 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#234]
**What is the problem?**
At the moment the Smart ID feature takes me to this error (see screenshot below)
<img width="1385" alt="Screenshot 2023-09-24 at 18 37 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/77fcfa28-3d36-4966-afb4-af3d5f7705a3">

**Why is this a problem?**
Cannot test Smart ID

**Possible solution.**
Let me know when Smart ID is configured with the Redesign

**Comment by ilmartyrk** [comment]
I need more info, what steps did you take, when did you get redirected to this page?

**Comment by BeccaMelhuish** [comment]
@ssin1901 Am also interested to know what the context was, for the user testing :)

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish Smart-ID is working, but you have to use [Smart-ID demo app](https://play.google.com/store/apps/details?id=com.stagnationlab.sk&hl=et&gl=US) to register your own Smart-ID account. But you would need ID-card or Mobiil-ID for that.

Another option to just check if login or signing works is to use accounts listed in [here](https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#accounts)

Use EE as country code and use the number part from the document number field so instead of PNOEE-50001029996-MOCK-Q 
use  50001029996
