### ISSUE TITLE
UX: No "you're now logged-in" cue

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#345]
**What is the problem?**
I've logged in into the platform, and I don't know if I am, in fact, logged in - there's absolutely no visual cue to it. I only deducted I am logged in after reading down to "My topics", so probably I am in my account (but I'm still not sure), but that's definitely not the best UX.

And the second issue - there's no content on the page I've landed.

<img width="1440" alt="Screenshot 2023-11-17 at 10 48 59" src="https://github.com/citizenos/citizenos-fe/assets/34126353/594cb45d-12aa-4904-8b52-6945fd287087">

**Possible solution.**
I would expect to see my name and avatar at the top of the page somewhere (a'la "Hi Oksana!"), and also some content to start with.

**Comment by kevincrepin** [comment]
Actually the dashboard has this addressing and user's name at the top when you log in: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=0%3A1&type=design&node-id=47-14884&viewport=-173%2C-3068%2C0.5&t=JHpSYOgQ9KMMC2dE-1&scaling=scale-down&starting-point-node-id=29%3A13982&show-proto-sidebar=1&mode=design

About the empty page: also mentioned this already to Ilmar that it should direct to the dashboard. When I tested it directed back to the logged out page.

**Comment by oksks** [comment]
Thank you @kevincrepin, I've just tested and yes, it seems it was a temporary hiccup - I do get the hello + my name at the top of the screen, however it's only there in the first view, and there's no trace of being logged in upon clicking elsewhere.
We've discussed this with team and would really like an avatar to be present in any view, after logging in.

**Comment by kevincrepin** [comment]
First I though that this option had merit, it's a very common pattern: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=9561-81131&viewport=-5954%2C-12208%2C0.5&t=11WGEl3FADhqA9Va-1&scaling=scale-down&starting-point-node-id=9561%3A81131&show-proto-sidebar=1&mode=design

The only problem is that in a topic view, it doesn't work really well in context of the adjacent buttons, which are related to the topic itself: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=2804-112414&viewport=-5954%2C-12208%2C0.5&t=11WGEl3FADhqA9Va-1&scaling=scale-down&starting-point-node-id=2804%3A112414&show-proto-sidebar=1&mode=design

We could move those topic button next to the topic activity. And move the role indication to the information for example. But this solution requires a bit more changes...


Alternatively we can bring the profile into the left side bar, as we currently have it. Would also be very recognisable for current users then of course: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=9596-63258&viewport=-5954%2C-12208%2C0.5&t=11WGEl3FADhqA9Va-1&scaling=scale-down&starting-point-node-id=2804%3A112414&show-proto-sidebar=1&mode=design
In order to reduce the cluttered feeling from the side menu though, I would then remove the topic breakdown (discussion, ideation, voting, followup) and just have "my topics".


We can even take this further – if we really want to bring the "log out" function as close as possible, without adding it to the menu itself: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=9596-69593&viewport=-5954%2C-12208%2C0.5&t=11WGEl3FADhqA9Va-1&scaling=scale-down&starting-point-node-id=9596%3A69593&show-proto-sidebar=1&mode=design
You can click on "My profile".

**Comment by anettlinno** [comment]
Thanks @kevincrepin !
I really love the version which is similar to our current platform -- where the profile is on the left menu bar. I think it´s convenient to our current Users. Also, I think log out under the profile is logical: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/d6c9ef7a-d713-46db-b054-aa6f144f0dab)

**Comment by oksks** [comment]
Plus one to @anettlinno's comment - the last version is brilliant. Beautiful UX 🙏

**Comment by oksks** [comment]
@ilmartyrk, could you pls implement this when possible 🤗🙏

**Comment by kevincrepin** [comment]
@ilmartyrk small detail but the divider lines colour in the menu in this version have changed from #E1E7EE to #EBF4FB

**Comment by anettlinno** [comment]
Leaving mark to issue #401 which will be solved with this issue

**Comment by ilmartyrk** [comment]
@kevincrepin , imlemented for desktop view, but not sure how it should look like on tablet and mobile. Can you check and make changes if needed

**Comment by BeccaMelhuish** [comment]
Just to add my two-pence here (wasn't following this topic, just saw it on redesign test): to me the dropdown feels as though this is where you can switch between your profiles, like how Toggl do it with switching workspaces.
But maybe one day we can add switching profiles here, if we're able to? :)   

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/afae0018-10d0-4ffa-b605-94cc035eed24)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/afb97962-2a3b-46e4-b9ed-b25bf28e0d26)

Also, what are people's thoughts on adding 'Notifications' to this menu, to make it a little easier to access/notice? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e9e92071-8c29-463f-adb8-5dae1056d563)

**Comment by anettlinno** [comment]
Triage 95. @kevincrepin we are missing tablet and mobile views here :) Please do your magic 🥇

**Comment by kevincrepin** [comment]
Added mobile: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=10435-86402&viewport=-12190%2C-32886%2C1&t=nV4Ix0WWo7QnNQb0-1&scaling=scale-down&starting-point-node-id=10435%3A86402&show-proto-sidebar=1&mode=design

And tablet: https://www.figma.com/proto/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?page-id=3094%3A111670&type=design&node-id=10455-97180&viewport=-12190%2C-32886%2C1&t=nV4Ix0WWo7QnNQb0-1&scaling=scale-down&starting-point-node-id=10455%3A97180&show-proto-sidebar=1&mode=design

In case of open topic: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=10435%3A87575&mode=design&t=tWET1vUHLcPj8TH9-1

**Comment by anettlinno** [comment]
Thanks! Looks good! Sending it To Do.
