### ISSUE TITLE
Wrong error message (from argument writing view) displayed in profile view

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#358]
**What is the problem?**
I've interacted with a topic - started writing an argument - and probably maxed out in the argument body field, but then closed that window (clicking on X) and clicked on Profile, in order to log out of my account.
At the top of my profile, the error message was continuously displayed, saying "Sorry, this statement text is too long", which wasn't applicable to the page I'm on at all.

<img width="1440" alt="Screenshot 2023-11-17 at 11 27 43" src="https://github.com/citizenos/citizenos-fe/assets/34126353/a53ca68e-6736-4e8d-99dd-31e5b818af6c">

Mac, Chrome. Reproduceable.

**Comment by ilmartyrk** [comment]
@kevincrepin  What do you think how we should handle norifivcation messages. Make them fade away after x seconds, or just close all after navigating away

**Comment by kevincrepin** [comment]
We probably have different categories: persistent and non-persistent. 

Persistent ones could be like "tomorrow our server will be down from 00:00 to 02:00. etc etc". These should be visible even if you click through the platform from one page to another. It can be closed manually by pressing X, but it doesn't disappear automatically.

Non-persistent ones are notifications that are only relevant within the context (or page) and these should not remain when you click away from the page, like in @oksks example. These can be closed manually by pressing X. 

Within non-persistent there are additional subcategories based on the type of notification (success, error, neutral/informational, warning). My feeling is that only the success subcategory could disappear after x seconds. Because everything is ok, so the user doesn't actually need to worry or be distracted. But if this is the only case then it's a bit of an exception... Which is also not idea. So maybe let's never do it that the notification disappears by itself, only by user interaction and in non-persistent cases by navigating away from the screen where it is originally shown.

Hope that makes sense @ilmartyrk :)

**Comment by ilmartyrk** [comment]
@kevincrepin , makes sense :)
