### ISSUE TITLE
Beginning of tours - new and returning and potential users 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#400]
Hi @kevincrepin @ilmartyrk @anettlinno @MeelikaH 

I noticed that we have a bit of a difference in angle between the beginning of the dashboard tour and the topic tour currently: 

The first tour you get to - the dashboard tour - doesn't mention the changes to the design, it's written more as if you have just come to Citizen OS for the first time ever (not the first time it looks like this): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8cdc3240-626f-4343-adf1-fb2e0920d23c)

And the second tour - the topic tour - does talk about the redesign, and written more from the perspective of showing you what's changed:

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/69535622-0f74-41dd-ba7e-a739c391a48b)

I'm thinking we might need two slightly different tours:

- One for new users who have never used the platform in its current state, which just offers them a tour as a newbie here
- One for returning users, which explains that we have made changes to the platform and want to show them what's new

@ilmartyrk how hard would this be to implement? If to tricky we can try to just come up with some copy that works for both. 

Would also be great to think about what sort of tour we could give logged out users - as discussed for the launch comms, and marketing in general (in the place of a demo video, potentially). Is there a way we could have an URL, that when followed takes them to the logged out dashboard, and gives them a mini-tour based on whatever is visible there (i.e. public groups, public topics, etc), then guides them to create an account to continue the tour of the logged in version?

**Comment by ilmartyrk** [comment]
@MeelikaH @kevincrepin @anettlinno Implementation is not too difficult, not sure if it needs any design changes too or just different texts

**Comment by anettlinno** [comment]
If implementation does not take too much time, then I support different approach to newbies and oldies. @ilmartyrk could you estimate the dev time please?

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I think it would just be different texts in the two places I screenshot above rather than any design changes, unless @kevincrepin has other thoughts :) 

What about a logged out tour that would be set off when following a certain URL, would this be more complicated?

**Comment by anettlinno** [comment]
@BeccaMelhuish re the logged out tour I think one of the ideas was to create COS platform overview chunk (similar to the product page on the website, but this could be more concentrating on the question _How to use the platform_ (whereas product page is answering to the question _What COS is_). We talked that these could include videos, pictures etc.

IF we decide to additionally have a separate tour for logged out users, then I would suggest that it wouldn´t be a pop-up, but something that Users need to choose to see. Otherwise it´s super annoying if there is the tour always popping up. In case we can only show it once to everyone, then let´s go for that solution :)

**Comment by BeccaMelhuish** [comment]
@anettlinno yes true - needs some thinking through re how we'd want it to work anyway :)

**Comment by kevincrepin** [comment]
In my mind these  "wizards" of walkthroughs are indeed for everyone after the new platform goes live, but they can address new users and existing users differently. The point is that for everyone, new or existing, the platform has changed so we want to offer to all the opportunity to take the helping hand the first time. 

So for any topic you first open (whether you created or just "entered" one) there would be the walkthrough. This would happen only the first time and then we can store it in cache that you have seen this. But we can also consider that for the first x weeks/months it could be so that if you clear your cache/cookies and then you return, that we still interpret that it's your first time.

**Comment by anettlinno** [comment]
@kevincrepin the tours will be provided for both -- new users and excising users, but the idea was to make two different versions in how we address our Users. If new Users, we speak with them from the perspective that "come and learn about the platform" and if returning Users, we´ll tell them what has changed :)  

OR we might find text that does not differ new and existing Users but is working for both groups @BeccaMelhuish 

Everyone will get the tour.

**Comment by BeccaMelhuish** [comment]
OK great, all sounds good to me - except for the problem of whether you are admin/editor or not for a topic, for the topic tour. As if you are admin/editor of a topic I think you'll see slightly different things on the tour, and if the tour will be telling you about things you can't do if you're just a participant (like edit, close, invite - I believe?). E.g.: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cecf4582-1f5d-4f72-a76c-f4c022963fb1)
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a92ed578-f61a-4ade-b8cb-43d213accea1)

We can try to solve this with wording, though it would be a bit clumsy, e.g. "Here topic admins or editors can manage participants and invite new people." (But in this case there would presumably be no "Invite & share" button visible, if they're in a private topic that they only have participant rights for, so would look a bit odd.) 

Another option is two different tours with different texts depending on your rights within whichever topic you are touring? 

For the general dashboard tours though, I can have a think if there's some wording that would make it work for both new and returning users, but if not we can just edit the first text of the tour (the "Hey X, welcome to Citizen OS!" pop-up) :)

**Comment by MeelikaH** [comment]
@BeccaMelhuish @anettlinno @ilmartyrk and @kevincrepin Reading this I'm wondering that the roles of the users might not be static. Some participant might want to be aware that they can also be admins and what that would include if they went for that at some point. It's always very important for admins to understand what the experience is for the participants without admin rights (so they can coordinate). Otherwise some admins might assume participants without admin rights get to do or see something they actually can't and this might create a messy communication. Would that be a risk in your opinion as well?

In regard of the tour, maybe we can somehow design two steps both go through. 
1) Topic tour - the admin way!
Explanation what and how, briefly.

2) Topic tour - participants view
Explanation what and how, briefly.

One more step, but as a new user or user who might become somebody who grows to a moderator role, I'd want to be aware of these steps and possibilities.

**Comment by BeccaMelhuish** [comment]
Very good points @MeelikaH! I agree it's good to show both to everyone :) 

Only issue is that when you are taking a tour, it gives you a tour of the topic you are in right then, with whatever view of it you have based on your rights. So would need some thought how to do it well.. Will have a think myself but maybe @kevincrepin has some ideas :)

**Comment by kevincrepin** [comment]
I feel it's getting maybe a bit too complicated :) 

Can we just have 2 different walkthroughs with slight edits based on the functionality available to your role within that topic? I think we would still go through all the steps because the "more" menu still holds functions for regular user also, and so does the participants section. Then if someone becomes an admin later I  would take a leap of faith and assume (the mother of all ****-ups :)) they might explore these sections to find what they're looking for.

OR we have 3 versions:

- first timer participant role
- first timer admin role
- previously first timer participant is now admin and has dedicated shortened walkthrough that shows the extra functionality available to them in their new role

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin @anettlinno I suggest we keep the current 2 and review after user testing
Reasons:
- Dashboard is a completely new view, we didn't have a dashboard on our previous versions 
- All menu items should be visible in the tour, even if they are not accessible for users if they don't have certain permissions, this will give them knowledge that these are possible actions they could take
- I don't think that our users are dumb enough to not understand that they cannot manage topics that they haven't got admin permissions

**Comment by anettlinno** [comment]
I very much agree with @ilmartyrk and @kevincrepin to keep it simple for the same arguments that Ilmar and Kevin have brought out. Providing separate tours for New Users and Oldies is already enough IMHO and I also agree that much has changed on the platform that everyone should know about. It would be strange if we leave out huge amount of Users in not showing them what the platform is designed for, only because they were invited into topic discussion and have lighter role :) 

If you go to Miro or any other tool, you also get an overview from all their features, not only certain ones (if I have chosen specific templates for example). So, I think it´s quite common behavior.

Agree to add this into user tests @BeccaMelhuish 

So, let´s go with new and returning users tour for now and keep ourselves open for the feedback from user tests :)

**Comment by anettlinno** [comment]
> We can try to solve this with wording, though it would be a bit clumsy, e.g. "Here topic admins or editors can manage participants and invite new people." (But in this case there would presumably be no "Invite & share" button visible, if they're in a private topic that they only have participant rights for, so would look a bit odd.)
> 
Agree that we can try to solve this with wording if we want to emphasize that certain actions are available only for admin users

**Comment by BeccaMelhuish** [comment]
Hello! 

Couple of things I got confused with here :) 

- I understood from @ilmartyrk that he's proposing we stick with just the two tours we currently have - dashboard and topic tours, and that we make the text applicable to everyone (newbies, oldies, admins, others) - is that right? 
- But I understood from @anettlinno you're vote is for splitting the two we have into newbies and oldies - so 4 in total (dashboard newbies, dashboard oldies, topic newbies, topic oldies) - is that right? 
- If so, then which do we go with? :) 
- I'm a bit confused by what @ilmartyrk was saying re: "All menu items should be visible in the tour, even if they are not accessible for users if they don't have certain permissions". As I thought the way the tours worked is that it walks you around whatever is on your screen, and if you only have participant rights then what's on your screen will be quite different to what's on an admins screen. E.g. if I'm not mistaken in [this issue](https://github.com/citizenos/citizenos-fe/issues/422#issuecomment-1825422247), there wouldn't be any sign of being able to invite/manage participants. And the top right '3 dots' menu just looks like this for a participant currently, just 'Favourite'. Which isn't a big problem, as in the copy we can say "Admins or editors can X', but just wanted to check we all have the same idea of how the tours work/will work :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/13b4191b-345d-4d22-b64a-644fac1e89e1)

**Comment by kevincrepin** [comment]
The dashboard and topic are new (design) for everyone, so there are no "oldies" I would say. And we should show the tour only first time you come on dashboard or open a topic, so there's no repeating.

**Comment by BeccaMelhuish** [comment]
Ok cool :) 
Will (at some point soon hopefully) try to edit the texts to work for both kinds of new (brand-new and second-hand new :D) and for all participant levels then :) 
(E.g. Admins and editors can do X here).

**Comment by anettlinno** [comment]
Triage 95. In Redesign Phase I let´s only keep these two tours that we already have implemented. This could be tested with Users to find out if this is sufficient or we need to create different tours for different user groups. 
Closing this issue with no further action. Let´s come back to it after user tests if needed.

**Comment by BeccaMelhuish** [comment]
@anettlinno It's not fully completed as if we're just keeping the two I need to re-work the texts based on what we agreed - that the text should work for both new and second-hand users, and for all participant levels - as currently it's not working for everyone/every context, but I will continue the conversation [here](https://github.com/citizenos/citizenos-fe/issues/355) in the issue Meelika opened :)
