### ISSUE TITLE
UX Issue: Logout button is very difficult to find 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#401]
**What is the problem?**
When we ran group tests on 17.11.2023, nobody from the team could find the Logout button without being instructed that it was in the Profile section (see screenshot)

<img width="1325" alt="Screenshot 2023-11-19 at 17 55 05" src="https://github.com/citizenos/citizenos-fe/assets/72747107/b0eaebd4-4b3e-4b4c-b37f-cd72794c24c5">

**Why is this a problem?**
Users should be able to easily find the logout button, as it is important for account security. 

**Possible solution.**
@kevincrepin @anettlinno, given that not a single person from the team was able to find the Logout button without directions – can we already consider changing the location of the Logout button?

**Comment by anettlinno** [comment]
Yes, this is very crucial issue. Users should be able to log out easily (imagine someone using public computer or friend´s laptop and cannot find logout button). @kevincrepin we were thinking of adding it to the left menu where it is currently located: 
![image](https://github.com/citizenos/citizenos-fe/assets/45175679/154dffcf-c8a8-452f-bd48-2e2058659ddb)
 WDYT?

**Comment by kevincrepin** [comment]
Would actually be nice to understand a bit more the user's behaviour. Did they not ever go to profile? Or did they not know there is a profile button in the menu? Or did they go and didn't see the log out button on the top right?

Because it's quite common to have the log out under the account/profile. So it's interesting to see no one had that idea to go to profile (to log out of your profile) :)

Anyway, through some of these additional questions I figured a lack of a visible "my profile" button could alleviate this issue – hopefully. So I'm connecting it with this issue: https://github.com/citizenos/citizenos-fe/issues/345#event-10992646822

**Comment by anettlinno** [comment]
In case we implement #345, we solve this issue as well :)

**Comment by ssin1901** [comment]
> Would actually be nice to understand a bit more the user's behaviour. Did they not ever go to profile? Or did they not know there is a profile button in the menu? Or did they go and didn't see the log out button on the top right?
> 
> Because it's quite common to have the log out under the account/profile. So it's interesting to see no one had that idea to go to profile (to log out of your profile) :)
> 
> Anyway, through some of these additional questions I figured a lack of a visible "my profile" button could alleviate this issue – hopefully. So I'm connecting it with this issue: [#345 (comment)](https://github.com/citizenos/citizenos-fe/issues/345#event-10992646822)

@kevincrepin thanks for everything and sorry for taking long to get back to you! We were group testing the Redesign application and the tests included Logout as well as well as changing information under Profile. 

In the first case, they couldn't find the Logout button to complete the task. In the second case they were focusing on the Profile task and therefore missed the Logout button on the right.

I support #345

**Comment by anettlinno** [comment]
Closing this issue as this will be solved in issue #345
