### ISSUE TITLE
Invite via email is missing email text

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#424]
**What is the user story?**
I wanted to invite someone to the public group and after clicking on the invite button, pop-up window appears. BUT the place where to insert email address has "Search" text. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/38beddd0-a6c1-4e6b-b068-bfcc77a83ee2)

Email field is missing text "Invite user via their username or email address" as is in Figma files: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/dc770a83-747d-40bf-abeb-8690bb3134bf)

**Which feature needs to be updated and how?**
Please add explanatory text

**Additional information.**
N/A

**Comment by BeccaMelhuish** [comment]
This also came up in the UX test here (below), when the user was inviting someone to her group in the 'Create group' flow. (She didn't add any email address/username as she presumably was confused by the Search box). 

But I'm confused myself as this screenshot from the test shows this text wasn't there for her on Weds, but when I go to the same place myself now the text is there.. And the issue was completed on Monday, so should have been showing for her on Weds? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/df575e74-8db0-4d4d-b543-6a184cdbdf55)
