### ISSUE TITLE
INVITE & SHARE: Make invite user dropdown more visible? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#472]
@kevincrepin what do you think about making this more visible? Like a darker colour or something? 

A few times when typing in email addresses I hadn't realised it had popped up already, as it's rather pale (especially with a short username like ilmar): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7ea7050b-1ed4-4a4a-b13c-41c7fae754b4)

**Comment by kevincrepin** [comment]
Agreed, let's do it like this: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=524%3A62243&mode=design&t=XhYfZ8CqlYuuiM7a-1

I also removed the search icon from there @ilmartyrk because it doesn't really always apply.

![search](https://github.com/citizenos/citizenos-fe/assets/26792281/0bca2cab-f43c-4b61-a5b3-7a9b6b153e18)

**Comment by ilmartyrk** [comment]
@kevincrepin is this like a general change or for only places where we allow searching for users (group, topic member/editor 
invites)?

**Comment by kevincrepin** [comment]
@ilmartyrk can you show me similar places? 

I would say in group members list for example when searching the list should just be updated so you see the results from there. (like currently in groups also).

Searching in arguments should have its own specific search logic (as defined in the components.

But the active state (black border) has always been there in designs.

**Comment by ilmartyrk** [comment]
@BeccaMelhuish should be fixed now. @kevincrepin you are right I didn't notice it before
