### ISSUE TITLE
DISCUSSION: No way to hide edits to an argument once opened

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#473]
When you view the edits on an argument, there's no way to hide them again: 
Input from @kevincrepin needed? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c374444c-5420-4ae1-9ab0-09a06a0a27fb)

**Comment by BeccaMelhuish** [comment]
(Also wondering why we have a direct link, do people need to be able to direct link to an edited version?)

**Comment by kevincrepin** [comment]
This didn't exist yet in design, so added it now: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=137%3A30501&mode=design&t=XhYfZ8CqlYuuiM7a-1
![Edit](https://github.com/citizenos/citizenos-fe/assets/26792281/10957af1-b39e-4b8a-8ce5-c7acc878d773)

**Comment by BeccaMelhuish** [comment]
Great thank you! 
Any thoughts on the 'Direct link' in this case potentially being unnecessary clutter?  
@anettlinno @ilmartyrk might have thoughts on that too :)

**Comment by anettlinno** [comment]
@BeccaMelhuish just to be clear, the idea of the direct link is that if someone would like to share an argument (instead of whole topic) with third person, then one can copy direct link and send it. When inserting the link, user is directly landing on the argument which was shared. 

But I do agree that under the "Edits" direct link it is not necessary and should be removed.

PS! Reply editing is not working correctly. Created this issue #521

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno this should be fixed now

**Comment by BeccaMelhuish** [comment]
@ilmartyrk could we remove these too as Anett agreed above? :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cb31df2f-e3ba-415d-9b24-2507e4a7453b)
