### ISSUE TITLE
MISC: Add phase buttons should be clickable all over

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#507]
Currently you have to click on the text heading to activate it, but the button should be clickable all over I think @kevincrepin?

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/8ec4b89d-baa6-4551-8d4b-1d0be415cd05)

Though wondering what the tooltip 'i' buttons there are for, is there mean to be a pop-up help text?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this is fixed

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish closing because I tested the button in multiple places (see screenshot1) and it all worked (see screenshot2)

<img width="1212" alt="Screenshot 2024-02-05 at 11 24 59" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6ea4d3c9-e62b-47bd-8fff-f9b2d3eba0fe">

<img width="1209" alt="Screenshot 2024-02-05 at 11 25 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/65057c2c-88cf-443e-b855-8101c5c25cd9">

**Comment by ssin1901** [comment]
Closing due to the comment above
