### ISSUE TITLE
TOPIC: Time should be when published not created? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#516]
This one I just published at 15.45, and the time says 15.20 so I assume that's when I started making it (went away and came back to it). Makes more sense that's it's the date and time it's actually published though? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/2136ae84-af93-4e1b-bd58-4003475377d9)

**Comment by anettlinno** [comment]
I think this is not following the designs, @ilmartyrk ? Currently it also differs from what @BeccaMelhuish referred to:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/2e938ee9-a8db-4830-bb43-9e3d09d32821)


In designs we have it so that we have date when it was published (and not time) and we have time (on the bottom right corner) when the topic had latest activity (I think there goes topic editing and discussion)

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/2257e6e2-40eb-46c4-b62a-8cd9342c1cec)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish this should be fixed now

**Comment by anettlinno** [comment]
Tested and now works properly. Closing the issue.
