### ISSUE TITLE
Dashboard: 'Back to my topics' disorienting when you have none.  

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#547]
Currently when you are a new user with no topics, then you go into a public topic on the dashboard, then the back button option is to click "Back to my topics": 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c745574f-1177-48a1-a014-4b00352f2694)

But then you get this blank screen because you don't have any topics (and as you came from the dashboard, not actually from my topics, it's a bit disorienting - when it just happened to me I thought it wasn't loading properly): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/f7f79d82-831d-4305-818e-3fe1b8dc8afa)

@anettlinno, needs some input from Kevin probably, re how to solve it?  

I guess adding this box there as well as on the dashboard, would solve it to some extent (still a bit disorienting to go "back" to somewhere you actually have never been, but at least not so confusingly blank):

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/34e7fc1f-4390-48fe-bdfe-0b0c2808ea2f)

**Comment by anettlinno** [comment]
@ilmartyrk if User clicks on the "Back to public topics" one should land on the Public topics page (instead of My topics) and if User clicks on "Back to My topics" one should be brought back in My topics. 
"Back to my topics" works nicely, but "Back to public topics" is not working correctly.

@kevincrepin in logged-in views we currently have only returning user profile (with topics and groups) but we are missing new user view. I think what Becca proposed would be good solution ("You haven´t engaged in any topics yet") and would appreciate design there (and groups) as well :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno @kevincrepin it will be difficult to determine where the back button should take as topics use the same view. But for empty my topics view I think we can add the same element as in dashboard as Becca suggested, just without the create group button and also change text to match the view https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=135%3A27281&mode=dev

One possible solution would be to check if user has any topics and if not then display back to dashboard button instead of my topics

**Comment by anettlinno** [comment]
@ilmartyrk but isn´t it possible to determine from where User entered to the topic -- either from My topics or Public topics? And if this is determined then we´ll provide different "Back" going options -- either "Back to My topics" or "Back to Public Topics"

**Comment by anettlinno** [comment]
> But for empty my topics view I think we can add the same element as in dashboard as Becca suggested, just without the create group button and also change text to match the view https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?node-id=135%3A27281&mode=dev
> 

@BeccaMelhuish could you help with the copy please? :)

**Comment by ilmartyrk** [comment]
@anettlinno this is possible, but it very much depends on browser history, it might get messy with different browsers and also with refreshes etc. it could easily go out of hand

**Comment by anettlinno** [comment]
Triage 99. In Phase I current functionality is quite OK, so let´s go with that and keeping in mind that we need to find solution where users can return to the page they came from.

**Comment by kevincrepin** [comment]
The back button should not work as a browser back though. If the person comes from dashboard and goes into a public topic, the back button should lead them to the public topics. 

And for new users on dashboard we do have this view: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=29%3A13070&mode=design&t=mGZWYhdhylxuJwCW-1 
We populate with public topics/groups.

And in meantime we have these empty states also for my topics and my groups (via another issue) :)

**Comment by BeccaMelhuish** [comment]
I've made a [new issue](https://github.com/citizenos/citizenos-fe/issues/1525) for the back button problem, and will close this one now :)
