### ISSUE TITLE
DISCUSSION: widescreen preview is strange

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#554]
**What is the problem?**
Arguments part looks better, when it´s narrowed down -- better to read and better to participate. BUT opening argumentary on wide screen looks strange: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/4abfdae5-b3b0-4e38-8675-fa37839fffb1)

Doesn´t match with the designs: 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/e7c1500d-6d0f-4a0a-9f95-74d62e179174)

**Why is this a problem?**
It looks broken and if to scroll down in argumentary then sides are empty:

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/6ecfa867-0862-4827-8ef4-70eeebc9d168)

**Possible solution.**
Would it be possible to scale it to the screen somehow?

**Comment by kevincrepin** [comment]
I think there was a misunderstanding. The entire middle content should have a fixed width. Not only the comments within the discussion. We want to limit the width of the middle content (topic content) because we don't want text paragraphs to extend too long, making it hard to read the text. 

On bigger screens I would do it like this @ilmartyrk :

![Topic](https://github.com/citizenos/citizenos-fe/assets/26792281/c5ba4432-418e-47d3-bd54-76e290261882)

**Comment by anettlinno** [comment]
Thanks, @kevincrepin ! That could work, WDYT @ilmartyrk ?

Asking for a friend... :octocat:  Why is argumentary blue whereas in designs it´s green :))

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/f5a52c3a-4b45-48f1-9e2f-2864166e1b51)

**Comment by ilmartyrk** [comment]
@kevincrepin @anettlinno posted an updated, should be fixed now

**Comment by anettlinno** [comment]
Looks beautiful. Closing the issue as it´s solved.
