### ISSUE TITLE
INVITE & SHARE: update co-creator roles

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-fe#564]
Triage 96.
@kevincrepin we would need your design for **admin** co-creators view:
- joined
- pending
As currently we don´t have an option to separate online/offline users as in current designs. 

![image](https://github.com/citizenos/citizenos-fe/assets/45175679/588cc42e-0b76-40f4-9995-66dc8321b882)

@kevincrepin we agreed that **editors** cannot invite nor manage participants -- how would that look in the design? Removing "Manage" and "Invite co-creators" button or disable them?
AND if the list of co-creators gets very long, then how should this be solved? Either by "see more" or something else?

We are also missing design for disabled "Settings" preview with a message "Sorry, editors don´t have a permission for topic settings...". @kevincrepin we would need design for disabled page.

How does the preview look like if editors don´t have publishing rights? Shall we disable the "Publish topic" button or remove it entirely?

Let´s not allow editors to add topics in the group.

_Originally posted by @anettlinno in https://github.com/citizenos/citizenos-fe/issues/363#issuecomment-1851615660_

**Comment by kevincrepin** [comment]
I would remove the actions like we did in the topic view. I think this list can get quite long because on the right side there's nothing else, so I think it could be fine:

![Co-editors](https://github.com/citizenos/citizenos-fe/assets/26792281/fdce4cfa-db96-44bf-beb7-d74332aff216)


For the disabled settings I would use the same dialog we use for the topic text when that is locked, then we have similar logic:

![Discussion - Settings - Editor role](https://github.com/citizenos/citizenos-fe/assets/26792281/1d1a1bf1-a893-41a3-ae50-26776a7fd608)

And yes, disabling the publish topic button would work better than removing it:
![Discussion - 4](https://github.com/citizenos/citizenos-fe/assets/26792281/b86b374e-6e98-4525-a833-58cc9aeef96b)

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin @BeccaMelhuish currently only difference between admins and editors is that editors cannot change visibility (change between private/public) and they cannot change topic status (draft, inProgress, voting etc.). So for now I am not sure to just disable the fields they cannot interact with or to change the whole logic on the API side

**Comment by ilmartyrk** [comment]
@anettlinno @kevincrepin @BeccaMelhuish I think this issue is now solved.

**Comment by anettlinno** [comment]
Yes! Tested and works nicely! Closing the issue.
