### ISSUE TITLE
Group: One button for two actions (Create and Invite) should be separated 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#573]
@kevincrepin one small issue with the design that's come to my attention via the first UX test (but is more a "design bug" than a user comprehension issue, so will raise it here already) is that here we have one button for two actions. And there are cases where both those actions aren't relevant at the same time. 

For example in the (probably quite common) situation where the user wants to create their group before inviting anyone. In this case, they want to click "Create group" but they don't want to click "Send invites" (because they haven't added anyone to send invites to, because they will do this later). 

Can it be solved somehow, so that the button is only "Create group"? Perhaps it should be the same flow as with topics - you publish, and then there is a pop-up to invite now or later if you want to? Or the "Send invites" button can be higher up on this same page? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/e2f22023-5cfa-48f2-921b-c2018012e633)

**Comment by kevincrepin** [comment]
Hmm, fair point about the user comprehension and indeed if they don't fill in any invitees yet at this stage they should still be able to create the group. I'm ok with renaming the button to just "Create group". 

But we can't have a separate inviting action within group creating because then you send invites to a group that has not been created yet.

And thinking about the idea of, similar to topic creation, having the invite after the group creation. Because members are an inherit part of a group, this inviting step should still be part of the process in my opinion. And then it's also weird to show this popup again if user explicitly decided not to invite members during this process. And if they **did** add members in this process it would also be weird to again ask to invite after the group creation...

So I'm thinking maybe all we need to do here is rename the button, allow users to create groups without already inviting members and then after group creation make the assumption that they will find from where they can invite members. If they haven't invited members after x-time we could also send them a reminder "A group without member is like a [insert funny analogy here]" :)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish I suggest that I add a check if any members are added to the "waiting list" and depending on that we show different texts for the button. So if any members are added we show the current create and invite and if not then it is just create

**Comment by kevincrepin** [comment]
That also sounds like a good solution @ilmartyrk .

**Comment by ilmartyrk** [comment]
@BeccaMelhuish changed the button text behavior as describe before

**Comment by BeccaMelhuish** [comment]
Just checked an all looks great thanks both! Found a bug but have made a separate [issue](https://github.com/citizenos/citizenos-fe/issues/584)

**Comment by BeccaMelhuish** [comment]
@ilmartyrk Though actually, what the bug didn't allow me to see was whether there is an "Invites sent!" message that pops up to show they have been sent after publishing. I saw for a second some sort of "Your group has been created" message, but I imagine we'll need different messages depending on whether someone has or hasn't invited people? (I.e. one along the lines of "Your group has been created and invites sent" and one more "Your group has been created, you can invite people at any time")

**Comment by BeccaMelhuish** [comment]
I created a [new issue](https://github.com/citizenos/citizenos-fe/issues/1527) for the final question, and will close this one :)
