### ISSUE TITLE
📱Mobile menu improvement

### ISSUE THREAD

**Issue by kevincrepin** [citizenos/citizenos-fe#615]
Going through the design review I realised that the design didn't account for the floating Help Centre button. On desktop it's not so intrusive but on the limited space of a phone it's quite annoying. Additionally we have a floating button logic to add a comment in the discussion, so then we have 2 floating buttons and it's quite a mess.

So I want to suggest an update to the top menu so it can hold the Help Centre. This way it still is always accessible, and it's no longer overlaying content. Of course in the top menu we already have the logo, the burger menu, the user's profile photo and the search. Adding another menu item to this is quite impossible. Since the search is less important than the Help Centre, I would suggest we move this to the burger menu.

Below is the update to the design and also available in Figma: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=11064%3A30687&mode=design&t=hMuZBFiOM13BzsmK-1
![Screenshot 2024-01-09 at 11 07 13](https://github.com/citizenos/citizenos-fe/assets/26792281/c07fbc98-94f0-40cf-bb16-f72b5440004e)

This is a new update, hence the "Enhancement" tag and I leave it up to @ilmartyrk and @anettlinno to decide if this priority, but at the moment the mobile experience is quite hindered by this Help Centre floating button, in my opinion.

**Comment by anettlinno** [comment]
@kevincrepin from user´s perspective I would say that search is more important in top menu than help center. I played around in phone and if I want to go to a certain topic or group, I need to find it by filtering under My Topics or just scrolling through topics. But if I´m in hurry and beginner User, it would be much easier to go to search in top menu and just type the name of the topic or group. So, I would suggest that the **top menu would consist of logo, search, burger menu and profile.** 

And Help Center in burger menu under Help looks logical place as well, because (hopefully) people need help less then search :) 

But I would love to hear @ilmartyrk´s thoughts as well here :)

**Comment by kevincrepin** [comment]
So if I understand correctly then the solution would be just to get rid of the Help Centre floating button entirely and only have it in the burger menu?

**Comment by ilmartyrk** [comment]
I personally like this solution and I believe that search is still findable and in a logical place, I already implemented these changes and I guess user tests can reflect if it is confusing or not

**Comment by anettlinno** [comment]
If so @ilmartyrk then let´s leave it as it is.
