### ISSUE TITLE
Voting: Potential problems with 'When all votes are in' 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#641]
@kevincrepin @ilmartyrk @anettlinno Making a separate issue for this one which has come out of thinking through [this issue](https://github.com/citizenos/citizenos-fe/issues/595) here. Less urgent to sort for the tests, but I think an important one to think about: 

Am I right in remembering that we previously discussed there were issues with this option, and decided to remove it? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/399e7c84-f40d-42a6-9a62-3cc763eea07c)

One issue I can see myself is that what the admin considers as "all votes being in" might be different to what the user considers as all votes are in. 

Some examples: 
- Someone sets up the vote, and votes themselves, before inviting anyone else. As far as the system is concerned, 1 of 1 votes are in, so it closes? 
- Someone sets up the vote and invites 10 people. 5 people join and vote on day 1. Which means 5 out of 5 people who have joined have voted, so it closes? But on day 2, the other 5 people would have wanted to join and vote. 
- Someone sets up the vote and invites 5 people via email, but also shares the link with a WhatsApp group. The 5 people who were invited directly vote, so the vote closes, but there were still people who wanted to use the share link who haven't yet voted.  

Obviously we could say it is up to the user to think through such scenarios when choosing what kind of 'vote ending' to go with, but I think it leaves a lot of potential for mishaps and frustration?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @anettlinno yes there are multiple issues related to that option. I'll remove it for now as it is also removed from our current version and we will come back to it in the later phases.

**Comment by BeccaMelhuish** [comment]
OK thank you! I have added phase II tag then to keep it on the radar :)

**Comment by anettlinno** [comment]
@ilmartyrk I still see it in voting options, but yes, please remove it :) 

I think that where it could work is in private group voting topic. When topic is added in private group, then all group members have an access to the topic. All roles can vote and if then all group members (in our team´s case 10 people for example) have voted, our system automatically closes the voting. 

According to my knowledge, there hasn´t been much need for this feature, because if there´s a deadline, then voting will be closed anyway, if not, then admins close it manually. And I personally haven´t used it either... 

let´s remove it for now and leave it open for future developments. I´ll add it in UX/UI redesign "No status" column for later review and remove Phase II as I don´t feel it´s relevant to solve it in Phase II.
