### ISSUE TITLE
Misc: User confusion around icons 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#690]
@kevincrepin @anettlinno @ilmartyrk There is a bit of confusion around the icons in these two places: 

**Topic info icons:** 
- The public/private icons wasn't understood (for example, one user thought it meant 'locked', like not possible to edit), but I think this is partly solved already by this change below in issue #680, as it will be written next to it (and I can't think how else we would depict private in an icon?): 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c21e61c2-1b70-40f6-9277-7d3b60c50078)
- The pen icon is being understood as an 'edit' button here and on the 'topic card' (below), understandably as we use it interchangeably to mean both things ourselves, and I think it's often used to mean edit in other platforms? Maybe just a 'person' icon would work for 'Created by'? Or not sure what else?:  
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/b7e5cedd-c020-4e53-b6cc-89b1233c381d)
- The language icon people aren't really understanding when it is 'Not specified' (e.g. the world could mean 'domain'), but perhaps we can change the test to 'Language not set' (and therefore also 'Location not set'). Hopefully @oksks can advise how translatable this is?   

**Topic card icons:** 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/ac809ed8-f539-48ec-9c80-9e357aca5fe5)
- This one again, people are clicking as if it's an edit button, and also after using the platform myself for a few weeks I've only just learned that this means 'Last edit' rather than 'Created'! A user also showed they understood this to mean 'Created' at one point - saying there seemed to be a bug as they were all saying they were created 'a few seconds ago' (which actually probably was a bug, but not the point in this issue :D) 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/cabe37b0-16ed-419a-ba1e-405613b97d7c)

One user had a pretty reasonable suggestion, which is that when you hover over icons they should have an explanation of what they are. (That's what he'd expect, as for him that's quite common).

**Comment by anettlinno** [comment]
I would leave it to @kevincrepin to decide

**Comment by oksks** [comment]
Thinking.. Instead of "Location not set" and "Language not set", perhaps we could use "Set topic language" and "Set topic location" as a CTA?

**Comment by BeccaMelhuish** [comment]
Ah it shows for participants as well though, so if so would have to be different views for admins/editors versus participants. And would have to have buttons to the relevant place to set them (I feel?), which from this issue #680 I think we're trying to avoid (to keep things clean), but up to @kevincrepin indeed :)

**Comment by kevincrepin** [comment]
We could change the author's icon to this one:
![Screenshot 2024-01-26 at 09 10 46](https://github.com/citizenos/citizenos-fe/assets/26792281/b8e0f6b4-8117-4279-ab81-37c87e59fa4b)
@ilmartyrk it's available here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=2%3A5647&mode=design&t=yoDKb7xLADti0hlu-1 

And for me the language icon confusion would be solved if we just have a label "language not set". Like @BeccaMelhuish mentioned we anyways need a label for regular users as they wouldn't see the CTA and tbh I'd rather let the admin figure out that they can set it when they edit the topic. Otherwise we can put CTA's everywhere where there's any option to do anything and we already have a lot of interaction possibilities :)

I think for me the topic card icon is not really an issue. Even if someone would click it expecting an action, after one try they'll understand that this is not an action to make here. 

And also not a fan of having hover tooltips for all icons. I don't think we have such specific unknown icons that they warrant that. And where there's an interaction possible the icon has a label also (action menus etc) so should be understandable there.

But of course if it's a recurring issue for users then we can consider it.

**Comment by BeccaMelhuish** [comment]
@kevincrepin OK yes sounds sensible to me! 

So we just change:

- 'Created by' icon
- Language not set / Location not set 

The only thing that I feel still could use clearing up could be this - the clarity of the bottom one meaning 'Last edited' rather than 'Created', but we can also leave it and see if it causes any issues :) 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c4b96373-83ab-4638-a6af-c10ed9a724ae)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish updated the icons and texts lets not touch the topicbox for now

**Comment by ssin1901** [comment]
I think it alright now as text has changed to "Language not set" and "Location not set" (screenshot attached)
<img width="1440" alt="Screenshot 2024-03-27 at 13 19 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/aede739e-a6c6-436b-8479-71425867c3aa">
