### ISSUE TITLE
Topic: Attachment(s) not showing in preview

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#691]
@kevincrepin @anettlinno @ilmartyrk  A user pointed out that when previewing his topic before publishing, it didn't show his attachment, so he wasn't sure if it had been successfully added. (He added a hyperlink, which shows, below, but also added an attachment, which doesn't). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/c34697cb-f2aa-4824-ac4e-f204036014d5)

**Comment by kevincrepin** [comment]
Very good point and embarrassing from my end, but indeed in the preview design right now there's no indication of attachments. This is because in the published state, the attachments show in the topic info card, whereas during composing they are added under the topic text. And so somehow they were left behind...

It actually raises the point that maybe this entire topic info card should also be visible in the preview state? And whether the co-creators card should be visible in the preview state... Since nothing here can actually be "done" and it's purely a preview, I think we could remove it from here and have the topic info card.

![Screenshot 2024-01-26 at 08 57 30](https://github.com/citizenos/citizenos-fe/assets/26792281/1af83a82-e476-4ec9-a1f2-e91e34e561ff)

Wdyt @BeccaMelhuish @ilmartyrk @anettlinno ?

**Comment by BeccaMelhuish** [comment]
@kevincrepin great yes! I think it makes sense to have the whole topic info box showing :) 

I wonder about losing the add co-creators at this point though as it seems quite a logical point to 'send it for review/input' to a colleague (or equivalent) before publishing - you've done what you think works, but you want to run it by team-mates and get their input. In which case they would be sending it for review, then saving as a draft. I wonder if we can add it as a button to the bottom bar before 'Save as draft'? Or under Topic info and above 'What's next', but collapsed unless they click it open?

**Comment by ssin1901** [comment]
@ilmartyrk I think this is fixed now (see screenshot)

<img width="1402" alt="Screenshot 2024-02-05 at 22 52 47" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e13d8514-1b70-48d4-bd38-4cb647e8e8fe">

**Comment by ilmartyrk** [comment]
Closing
