### ISSUE TITLE
Discussion: Report to admin pop-up needs a message for when no explanation entered

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#697]
When I try sending this with no explanation added, the button just becomes 'dead' - nothing happens when I click it.

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/06e41c8c-95ce-4555-ab47-978639f3c5dc)

It needs a message to tell the user "Please provide an explanation", I guess would be same UX as this one (or the red box around the field, I can't remember which @kevincrepin said is for which situation)? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/17f2e4ea-19c0-4f52-9dd3-ecadcc68c15a)

(Though without the big gap, must be a bug, will make a separate issue)

**Comment by kevincrepin** [comment]
I didn't know this field was actually mandatory...

We need to add an asterix then at least to the label, like with the dropdown above it.

And since it's a mandatory input field, if it's not filled in we need to show the field validation, similar to:
![Screenshot 2024-01-26 at 09 43 19](https://github.com/citizenos/citizenos-fe/assets/26792281/5aa2f84c-f216-4563-81d7-8940dd3673e1)

It's different from the search field because it's not the search field that you need to fill in. Bit specific situation with that one. Anyways if this text field is mandatory it needs to get the field validation when trying to submit.

**Comment by BeccaMelhuish** [comment]
Actually I just assumed it was mandatory because of what was happening, but maybe it doesn't need to be. @anettlinno wdyt? :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @kevincrepin I made some changes so it is more clear that it is a mandatory field

**Comment by ssin1901** [comment]
Seems alright for this phase (see screenshot). Closing now.
<img width="1440" alt="Screenshot 2024-03-27 at 13 23 13" src="https://github.com/citizenos/citizenos-fe/assets/72747107/26f0e1bd-4f46-4693-9847-b9913f044676">
