### ISSUE TITLE
VOTING: Voting topic in draft gets converted to a Discussion topic

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#716]
**What is the problem?**
When a user creates a voting topic (screenshot1) and doesn't publish it, and then later goes to My Topics to edit it (screenshot2) the topic has the Discussion Topic View (screenshot3). 

<img width="1440" alt="step1" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e355a51a-31c6-4562-aaca-d06ab530ff87">

<img width="1440" alt="step2" src="https://github.com/citizenos/citizenos-fe/assets/72747107/6e9d63f0-2b3c-487f-af37-5136107c91f7">

<img width="1440" alt="step3" src="https://github.com/citizenos/citizenos-fe/assets/72747107/2e0a6283-1310-4eff-8517-1632141c0be8">

NB! Replicated in both Safari and Chrome latest versions in incognito mode. 

**Why is this a problem?**
This is especially problematic because the user loses their saved voting settings and custom options (screenshot4).

<img width="1349" alt="Screenshot 2024-01-30 at 15 05 41" src="https://github.com/citizenos/citizenos-fe/assets/72747107/027c01b8-ce02-4615-8589-03ec83a0b511">

**Possible solution.**
@ilmartyrk @BeccaMelhuish maybe this was intended? In that case, just close with a comment

**Comment by ssin1901** [comment]
@ilmartyrk added the high priority label because a similar issue came up in #747 and has been replicated in Safari and Chrome.

Would not be good if a voting topic or draft got converted to a discussion topic because then the user will lose all of their content and get frustrated.

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish it is a little complex situation. In our current flow if you start creating a voting topic we take user to the view. Topic will be created straight away, but when user gets to the voting tab we actually post data to the serve after they click on the Continue button to move forward to the topic preview. This is because of all the required fields for creating a vote and having to be filled. If user moves to the preview and doesn't publish the topic it will be in draft status and it will open up as edit voting topic. 

@ssin1901 it is actually not related to https://github.com/citizenos/citizenos-fe/issues/747

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish I don't have a good fix for this, sending it to later phase

**Comment by ssin1901** [comment]
@ilmartyrk removing high priority label

**Comment by BeccaMelhuish** [comment]
@ssin1901 @ilmartyrk seems like quite a high priority one though from what I've understood? Seems messy and potential for causing quite some issues?

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 closing the issue as it is fixed though if a person has  not added vote info it will still get converted to discussion.

**Comment by BeccaMelhuish** [comment]
Ah @ilmartyrk, is there any way around that (converting to discussion if they haven't added vote)? As seems potentially very confusing, and quite possible that someone would set the text and save as draft (maybe to check with a colleague) without having added voting settings yet.
