### ISSUE TITLE
Groups: 'Back to group' when your browsing topics in a group. 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#753]
@kevincrepin @anettlinno @ilmartyrk 

I'm foreseeing a UX issue from the participants side when setting up a dummy public consultation for them to participate in. If you agree that it's common sense (rather than needing to wait for users to show if it's a problem), shall we try to fix it already? 

What I am guessing will happen is this: 

They start off in the group I have invited them to: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/4ffc8884-6099-4ef5-8a56-416aae88b562)

They then participate in the first topic. Once they're done they go back to go to the next one, using this button, but this takes them to their 'My topics' (which will be empty): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/1c5f648f-81bc-4b37-8741-2f5e89068576)

They'll then be a bit lost, and have to find their 'My groups', go back into the group, and then go into the next topic. 

Would it make sense (and is it technically possible @ilmartyrk?) if when they have come into a topic via a group, instead of 'Back to my topics', the button at the top is 'Back to Yourtown 2030 Visionaries' (in this case), or just 'Back to group' (if it's simpler)? This would seem more logical to me :)

**Comment by kevincrepin** [comment]
Seems like the confusion ic stemming from the "Back" in that sentence, because it's supposed to act like going deeper in a root structure. Going "back" just takes you to a higher level of that structure. 

It's not supposed to be like your browser's back button, which just takes you one step back in your journey. We can't and shouldn't mix up the two where in one case it does one and in another it does the other. 

In short term maybe we should jsut remove the word "back" from this label and just have "To my groups" or "To my topics". This wouldn't solve that the user in this case would maybe still easily want to go back to the group they started from though, but at least it would make it clearer that you're not going "back" as such.

This starting from a group and having the topic be part of the group creates some questions about the hierarchy where topics "exist" because currently we don't actually have a hierarchy, rather a flat one, I think, @ilmartyrk ?

Anyway, I think your request has merit, @BeccaMelhuish , but the solution requires adding conditions where we need to know where you're coming from previously, which, in my experience is quite a hassle. But correct me if I'm wrong @ilmartyrk !

**Comment by anettlinno** [comment]
Triage 100. Agree with Kevin that this feature is not the same as browser´s "back" button and technically it is complicated to direct users back to all their possible previous places (like what if one joins via invite link etc). 
We can change the copy to "Go to my topics" and "Go to my groups" which makes it more clear that it´s not directing user "back" to where she came. 

Sending to do. Est dev time 5 min.

**Comment by ilmartyrk** [comment]
@anettlinno @BeccaMelhuish updated the texts

**Comment by ssin1901** [comment]
Updated and closing (see screenshot)
<img width="1240" alt="Screenshot 2024-03-27 at 13 30 00" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7199def0-78d6-4b0f-8d1d-67923bc6d0b6">
