### ISSUE TITLE
Discussion: Contributions numbers to include replies? 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#794]
@kevincrepin I'm wondering if based on [this change](https://github.com/citizenos/citizenos-fe/issues/732) we need to make any changes here? I.e. to add in replies so the numbers add up to the total? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/25c8dbf7-6788-40a4-86b7-13c59723cd12)

(And in the case of this first one, might also help with an issue of some users recently thinking those were the vote results, as they had a yes-no type vote). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a843900c-dbeb-4395-be75-42ee468cd917)

I.e. like we do on the current platform for this part: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/24f29e53-5316-4109-b51a-b231e60c69c4)

**Comment by BeccaMelhuish** [comment]
I see it's like this now, so just flagging for review from @kevincrepin (unless he has already input elsewhere): 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7247eef8-3846-4df4-a180-a9b7c89ca082)

**Comment by kevincrepin** [comment]
I would put the reply count also in the right card and the "discussion sentiment" widget. I think then the line under Contributions "Pro: 2   Con: 1   Info: 1   Replies: 2" can be removed, because it's duplicating bit too much now.

![Screenshot 2024-03-06 at 10 45 02](https://github.com/citizenos/citizenos-fe/assets/26792281/00ec872c-6e21-4e1d-9e81-5f6ef4e8d54e)

**Comment by ilmartyrk** [comment]
@kevincrepin made a little tweak for the mobile as the items wouldn't fit ![Kuvatõmmis 2024-03-06 111524](https://github.com/citizenos/citizenos-fe/assets/19904307/f3320d66-8d03-4f7d-8427-ce494a0430e0)
