### ISSUE TITLE
MOBILE: Delete user icon in Invite and Share does not look right 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#802]
**What is the problem?**
_Tested with iPhone 6s Plus (5.5-inch screen, 414px × 736px viewport) on iOS 15.8.1

Tested with Simulator for iPhone 14 Plus - iOS (6.7-inch screen, 428px × 926px viewport) on iOS 16.2_

In "Invite Users" the delete icon does not look right (screenshot1 from iOS 6Plus)

<img width="511" alt="Screenshot 2024-02-09 at 14 17 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/d3a56bc2-520b-4601-b6b1-d1b2bea71179">

Replicated in iOS 14 Plus (see screenshot2)

<img width="399" alt="Screenshot 2024-02-09 at 14 18 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ae2eed69-878b-477e-a98d-e5fbf61e2861">

**Why is this a problem?**
UI needs to be reviewed 

**Possible solution.**
Needs input from UX team

**Comment by BeccaMelhuish** [comment]
Looks OK on my phone so I think it's just a bug, will remove the UX label :) 

(I do wonder a bit at the placement of the bin icon next to the rights rather than the name, but I don't think will cause any issues) 

![image](https://github.com/user-attachments/assets/621f4f67-61b0-403c-9f14-8b4e6ef5ccf2)

**Comment by ssin1901** [comment]
Seems fixed on iPhone 14 plus (screenshot1)

![Simulator Screen Shot - iPhone 14 Plus - 2024-09-25 at 15 02 13](https://github.com/user-attachments/assets/8e840581-3c15-4870-a538-886ec6bf2b95)
