### ISSUE TITLE
Group: Users are confused by Public and Private when it’s in a group

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#865]
**Round 2 insights:**

Somewhat (though I think not entirely) related to this issue #752, users are confused about the public/private options for topics when they are in a group. E.g. "Does it mean public public, or public to everyone in the group? Private to only certain people in the group?" One user seemed to think it might be related to access rights. 

**Suggestion:**

Needs consideration along with 752 in Phase II, but for the short-term @kevincrepin does it need a help button?

**Comment by kevincrepin** [comment]
Not sure if help button or just additional line of copy/more specific line of copy in this place.

![Screenshot 2024-02-13 at 18 05 42](https://github.com/citizenos/citizenos-fe/assets/26792281/cb04826b-a943-4701-b209-1f545500901b)

**Comment by BeccaMelhuish** [comment]
The thing is this is a bit complicated, in connection to the issue in #752, as depending on the flow of how people are creating their topic it will make sense / not make sense in different ways. 

So if someone is making the topic from scratch it makes sense to choose private or public, but if they have created it within a group, it's more confusing. If it's a public group, then it doesn't make sense that it would have a 'private' option (should this be greyed out in that case?). And if it's a private group then it doesn't make sense that it says public (again could it/should it be greyed out?). 

I think as an interim thing, until we have time to think it through more, we could change it to this? 
"Anyone in the world can participate"

**Comment by kevincrepin** [comment]
I guess the question is whether we know (from the technical side) if the topic is being created from a group – and thus would take over its visibility settings... @ilmartyrk ? Or is this topic only getting an extra parameter that preselect the group, but otherwise is like any other topic that you start from scratch?

If we do know then I completely agree with @BeccaMelhuish that we could disable one or the other visibility setting if the group's visibility overrides it anyway.

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish I updated the process so that if topic is created from group it will default to the group visibility (privat or public) and changing it is disabled. It will not work if user starts to edit the topic eg. it is saved as a draft, but at least it will solve the problem partly

**Comment by BeccaMelhuish** [comment]
@ilmartyrk I just tested it and they are both greyed out, is that how it's meant to be? My guess is that this would be quite confusing for users. 

Could it be that just the one that isn't selected is greyed out, e.g. in this case just the private box? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/a202c5c9-0794-43d1-89ff-8d611c4e410b)

**Comment by ssin1901** [comment]
@BeccaMelhuish just tested it and to me it makes sense that Private and Public are both greyed out because the user cannot take any action (i.e uncheck the option, select another option). Can we keep it as it is for this round of tests?

**Comment by ssin1901** [comment]
Closing this issue for now.

**Comment by kevincrepin** [comment]
There's also the additional section under the settings where we show the groups. So if I create a topic from within a group it automatically shows that group here. But I can also still remove the group :) At which point the Private/Public option also becomes again fully available, because this topic is effectively not belonging to any group right now.

That also made me think that I can also add this topic to multiple groups from here, which could be public or private. How does this now affect the public/private option? I think we completely overlooked this.

Of course we can also tweak this part so the user cannot remove the group or add any other groups. This would be the simplest way. But if you would also want to add this topic to other groups then it would make more sense to create the topic from the "baseline" create action.

![Screenshot 2024-11-15 at 14 52 21](https://github.com/user-attachments/assets/e1f7c451-c493-4a6a-b930-24de8b46d7db)
