### ISSUE TITLE
VOTING: UX and Functionality Issues caused by Neutral and Veto in Custom Options

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#874]
**What is the problem?**
If a topic admin wants to add "Neutral" or "Veto" to the vote, then the Min options should be default 1, since the user who selects "Neutral" or "Veto" should not have to check other options. 

However, _in a test in the latest version of Safari and Chrome_, the topic admin is able to add "Neutral" AND "Veto" AND set Min options to 4 (screenshot1)

<img width="1291" alt="Screenshot 2024-02-21 at 12 39 44" src="https://github.com/citizenos/citizenos-fe/assets/72747107/bcd7e58c-114f-4771-9bdc-b16fe31ff856">

Here are the UX and functionality issues caused by this

1. Veto does not appear as option despite being selected, **confusing the user(see screenshot2)**

<img width="1294" alt="Screenshot 2024-02-21 at 12 40 18" src="https://github.com/citizenos/citizenos-fe/assets/72747107/1e2f4e40-dd4b-4b6e-8c10-a0dc2cc57a80">

2. Later, when the vote is published, **all users are forced to select the Neutral option or Submit vote doesn't work** (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/f532b9dd-bbe9-4fd9-a854-059900468da5

**Possible solution.**
@ilmartyrk I think this flow should be discussed in one of our Product meetings. There are 3 separate issues related to this #789 #768 #754 so we should probably discuss it more detail.

**Comment by ilmartyrk** [comment]
@ssin1901 I am not sure if it needs more discussion, I can fix-it by just excluding the Neutral and Veto from Max-options number this way users cannot create this voting system as you managed in your test, also other issues you referred are fixed and sent to testing. On our API side everything should work as it is as Veto and Neutral can be sent even if you have the minimum options count set. Otherwise for example if your created vote requires min 2 options set, but we change the number to 1, then the vote would not work at all for the creator. Also  our UX disables the cast vote button if min number is not selected, but if user chooses Veto or Neutral it instantly deselects other options and enables casting vote so it is quite clear

**Comment by ssin1901** [comment]
@ilmartyrk this issue is fixed and everything now works perfectly (see screen recording)


https://github.com/citizenos/citizenos-fe/assets/72747107/24f59a63-ce72-408d-bb2d-cfdadf4a1993
