### ISSUE TITLE
Discussion: topic text missing on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#914]
Admin user on mobile (Android, Firefox), when going into the discussion tab on mobile (from the discussions button/block on topic main page) the topic text is missing, it should be at the top:  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/d24fb739-3bc2-4f40-9030-633cef745ad7)

(Please check for voting and follow-up on mobile too, should all be the same as desktop - with topic text at the top).

**Comment by BeccaMelhuish** [comment]
Can confirm now was the same prob in voting tab: 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/7a6c24a8-a31e-4b75-9a02-aa2ab9d04bd1)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish not a bug, this is by design, topic content can be viewed from the first bottom menu button, for other items it is the title only

**Comment by BeccaMelhuish** [comment]
Ah OK! Then I will reopen it as a user insight issue, and ask @kevincrepin to review. As the topic text is needed at the top to tell people what they are discussing I think? This was the feedback from a user test (admin, on mobile) - only from 1 test so far, but having the text there seemed necessary enough for me to assume it was a bug :) 

For example, here is the topic text from the test, that was missing - it introduces the discussion, so would need to be above the discussion bit for people to know what they are doing I think? The user (figuring out how the process works in the admin role) was a bit lost until I explained (mistakenly) that it was a bug and the topic text should be there.  

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/72d16d68-ce3a-4b29-a64c-878a62af6c60)
 
Maybe having it there would cause some other issues though, and there's a reason it's excluded? If so we can try to test it more, but in my mind (and the user's in the test) it would be best if it's there?

**Comment by BeccaMelhuish** [comment]
We could also wait and see if it comes up in @ssin1901's participant mobile tests, then review when we have more insight :)

**Comment by kevincrepin** [comment]
This was indeed by design and I do understand that maybe it might not work. The reason behind it was that if we have the topic text visible in each "tab" it actually pushes down what you're supposed to interact with within that tab – discussion, ideation, voting, etc.... 

So the idea was to keep the long text and topic info all separate, you can read it all there and then move to the other tabs for the interaction. But this is/was the theory and indeed would be nice to see whether people catch up on this or not. Would be nice to find out whether they:

1. Understand the topic text is (only) accessible from the first tab. That it's not broken.
2. After they understand this whether this works for them or not really and they would actually rather see the topic text everywhere

And then we need to figure out a way that the discussion, ideation, voting, follow-up modules can still be found ;)

**Comment by ilmartyrk** [comment]
@kevincrepin @BeccaMelhuish moving it to in-prep as it might change in the future, but is not an issue that will block our initial launch

**Comment by BeccaMelhuish** [comment]
OK yes noted, thanks for the explanation! Will keep an eye on it in the tests and let's see :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish mention this issue in the phases issue and then close it

**Comment by kevincrepin** [comment]
Yes, when we have phase specific texts this will change. In fact it has already changed because we already have designs for this, but more on that later :)

**Comment by BeccaMelhuish** [comment]
Closing as will be covered by https://github.com/citizenos/citizenos-fe/issues/251
