### ISSUE TITLE
Misc: On mobile only 'Discussion' block takes you to 'Discussion' tab, Voting and Follow-up do not

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#920]
@ilmartyrk @kevincrepin Not sure if this is a bug or a UX thing, but a user noted that on mobile, clicking on the discussions block here takes you to the discussion, but when clicking on the other two, nothing happens. 

Should it be consistent for all 3 of them? I.e. when they are no longer an 'Add voting system' or 'Add follow-up' button, it becomes a 'Take me to voting' 'Take me to follow-up' button. (With no changes to the text on it, just the functionality). 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/228be347-f1b4-48ef-bd5c-7f2267ca372c)

Also @kevincrepin, should we have the same functionality for desktop? I have noted in the desktop tests that very consistently the users expect this to be a button (pretty much all of them have clicked on it, often multiple times as they are really expecting it to be a button), and from what I've seen having it work the same on desktop it does on mobile would be quite consistent with what they are expecting from it (so intuitive for them).

**Comment by kevincrepin** [comment]
I don't mind if they would be clickable.

Sidenote: We have this "light topic" design as a future iteration and there these cards don't exist at all anymore. This was because previous tests showed people didn't see really a lot of value in it and it was adding to the information noise.
I guess this can be revised later down the road.
