### ISSUE TITLE
Discussion: Jumps up when view reactions

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#965]
When you click on the reactions, it takes you right to the top of the topic. This will be a real pain for the users, as you totally lose where you were in the discussion. Pop-up should appear in the same places as you clicked. 

Before clicking: 
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/edff3429-2367-4cb5-9d48-5530d5e44813)

After clicking:
![image](https://github.com/citizenos/citizenos-fe/assets/61320526/31631840-c4f5-468b-87b8-901d534a86bc)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish posted a scrolling fix, as the general style with position fixed is added to the content in order to prevent background content scrolling and also allowing properly adding scroll for the dialog if needed I'll now store the window scroll position the moment the dialog is opened and will scroll back after closing the dialog. There might come some cases where this will have some issues like when multiple dialogs are opened at once, but lets deal with them later if any reports come in

**Comment by BeccaMelhuish** [comment]
Ah OK yes that works I think, thank you! At least they land back in the right place :)
