### ISSUE TITLE
TOPIC/GROUP: Issues for user who is invited via a share link

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#967]
**What is the problem?**
1. User Sara receives a link to join a Private Group via WhatsApp
2. User Sara clicks on the link and is directed to Create Account 
3. User Sara successfully creates an account and receives a verification email (screenshot1)
4. User Sara is directed to Login interface (screenshot2)
5. When she logs in, she is presented with this view (screenshot3)
6. She does not see the Private Group anywhere (since she didn't join it)
7. She may not realise that she needs to re enter the link from WhatsApp

<img width="707" alt="Screenshot 2024-03-11 at 16 10 27" src="https://github.com/citizenos/citizenos-fe/assets/72747107/852198c7-20ca-467b-bcb2-14660128bd20">

<img width="613" alt="Screenshot 2024-03-11 at 16 10 58" src="https://github.com/citizenos/citizenos-fe/assets/72747107/baa71965-4b5d-47d0-8dbf-4b4253e8df0d">

<img width="1094" alt="Screenshot 2024-03-11 at 16 12 56" src="https://github.com/citizenos/citizenos-fe/assets/72747107/e7b0af0c-0579-4dc2-ab84-80dc61eb9939">

**Why is this a problem?**
1. The user will not see the Private Group unless they enter the original share link into the URL, which 3/4 users did not remember to do in the user tests which I ran last week. 
2. The 4th user registered via Google and did not encounter this problem but had he tried email and password, it is possible he would also have gotten stuck at this point.

**Possible solution.**
@ilmartyrk a couple of possible solutions but really not sure how to fix it

1. After verifying account and logging in, user should be re directed to the private group that they originally entered
4. User should see the "shared" topic under My Groups without joining the private group. Since they wouldn't see the Private Group anyway, without the link.

**Comment by BeccaMelhuish** [comment]
A few additional points from me too :) 

The group in the user tests Sara mentioned was a public group, so we have the same problem here regardless of whether the link is to something public or private I believe, @ssin1901? So any of our share links. 

It's somewhat connected to [this issue](https://github.com/citizenos/citizenos-fe/issues/739), which was the same problem but via an email invite rather than a URL. 

Very much agree with Sara this is a high priority one, as a lot of use cases involve sharing an URL for a group or topic to new users, and it seems many of the users wouldn't end up accessing the group or topic they followed the link to. 

Adding the user insights tag too as this issue came from the tests :)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish @ssin1901 posted a fix, should appear in a few minutes

**Comment by ssin1901** [comment]
@BeccaMelhuish it got changed to a Private group.

**Comment by ssin1901** [comment]
<img width="1290" alt="Screenshot 2024-03-11 at 18 11 08" src="https://github.com/citizenos/citizenos-fe/assets/72747107/ecd72de8-87b5-461f-9cb6-9e4c38717df3">

**Comment by ilmartyrk** [comment]
@ssin1901 @BeccaMelhuish I updated the code so that if the register form is opened from the join link flow this join link will be posted together with the register flow and will get cyphered inside the token that is in the link we use for validating the e-mail. So if this redirect URL exists in the token user will get redirected to that link after clicking "Verify my email" button in the e-mail

**Comment by BeccaMelhuish** [comment]
@ilmartyrk awesome! :D 

I will leave @ssin1901 to test properly but this sounds a great fix to me :))

**Comment by ssin1901** [comment]
@ilmartyrk very happy with the fix and closing now (see screen recording)

https://github.com/citizenos/citizenos-fe/assets/72747107/7e06c239-c6dd-4c84-9ac4-ca7031f7a955
