### ISSUE TITLE
FOLLOW UP: Code in Topic Activity 

### ISSUE THREAD

**Issue by ssin1901** [citizenos/citizenos-fe#975]
**What is the problem?**
Code in the activity feed (see screenshot)
<img width="1292" alt="Screenshot 2024-03-12 at 12 10 54" src="https://github.com/citizenos/citizenos-fe/assets/72747107/7bc613a5-85c9-445e-a768-413ee10a727e">

**Why is this a problem?**
Confuses the user, also means that the activity is not displayed

**Possible solution.**
Code should be replaced by actual activity

**Comment by ilmartyrk** [comment]
@ssin1901 I could not find the action to get that string, can you get that for me

**Comment by ilmartyrk** [comment]
@ssin1901 ping

**Comment by ssin1901** [comment]
@ilmartyrk apologies. The original user (Maria or Ozzie, cannot remember) created a follow up update but the user saw code. It would be difficult to replicate the issue at this point though.

If possible, can you delete this topic from the database and we can just close the issue, and add a new one if it comes up again?
https://test.app.citizenos.com/en/topics/82bbbd90-200a-48e5-a0e4-f235245495f6#followUp

**Comment by ilmartyrk** [comment]
@ssin1901 no need to close the issue I can see the missing string now in that topics activity feed, seems to be for updating a follow-up event, so this issue is valid. As we have added some new functionalities here and there, there are probably other missing activity strings too, so I will close this issue when I've added the key and we'll create new issues when we stumble upon other
