### ISSUE TITLE
ARGUMENT: can't create ordered/unordered lists

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-fe#983]
**What is the problem?**
Tried to create a highly important list of 5 things I'd take to a desert island, and the listing feature doesn't work - nothing happens, when I type text after clicking on either of the buttons.

https://github.com/citizenos/citizenos-fe/assets/34126353/2a58a122-0d01-46f4-a73d-e643245a8772

**Comment by ilmartyrk** [comment]
@oksks will check, issue is related to the markdown editor that we use for arguments, Luckily not Etherpad issue.

**Comment by ilmartyrk** [comment]
@oksks @BeccaMelhuish @ssin1901 all these (https://github.com/citizenos/citizenos-fe/issues/997, https://github.com/citizenos/citizenos-fe/issues/937) issues are related to markdown formatting and should be fixed. The tags displayed around text are because of Markdown standard and the eye icon is for previewing your text. I initially removed the tags for formatting, but didn't notice it affected other items too.

**Comment by oksks** [comment]
@ilmartyrk this doesn't seem to be fixed, just checked

**Comment by BeccaMelhuish** [comment]
I found the same but sometimes there's a lag so will check a bit later too :)
