### ISSUE TITLE
Topics: Red error line too early in moderation pop-up 

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-fe#993]
As soon as you click in the dropdown to select something, you get the red error line and message. You haven't even got to that box, so is way too early. It should only appear when you click the greyed out button, to explain why it is grey? Or not at all? 

![image](https://github.com/citizenos/citizenos-fe/assets/61320526/61d4ddff-28b9-4c1f-ae70-1f098944472a)

**Comment by ilmartyrk** [comment]
@BeccaMelhuish there was a previous issue that I didn't bother to find that wanted this text field to be focused so that user can start typing, this will trigger the field validation. All grayed out buttons are fully disabled user clicks will not trigger any code. I updated the form validation and removed the focus from the textarea element so that the validation will not get triggered if an user decides to choose the reason first.
I believe that grayed out buttons are quite self explanatory for users that something is missing, specially in these cases where there are really few input elements.

**Comment by BeccaMelhuish** [comment]
@ilmartyrk OK yeah I agree about the greyed out buttons been self-explanatory in this case. So should we just remove the red message completely? It still pops up somehow for me, though when I click in a spot that might not often get clicked in (between drop-down and text field). A minor thing though, hopefully shouldn't happen often.

**Comment by ssin1901** [comment]
Moving to done because this works alright and also doesn't affect our users.
